import { uint8ArrayToBase64, generateContentHash } from '../../libs/utils/hashUtils.js';
// import { compareWithLastGenerated } from '../../libs/utils/hashTestUtils.js';

export async function verifyPDFReport(file) {
    return new Promise((resolve) => {
        const reader = new FileReader();
        
        reader.onload = async (e) => {
            try {
                const pdfContent = new Uint8Array(e.target.result);
                const contentStr = new TextDecoder().decode(pdfContent);
                
                // Find our verification content with more specific markers
                const startMarker = '---VERIFY_CONTENT_START---';
                const endMarker = '---VERIFY_CONTENT_END---';
                
                // Find the actual JSON content between markers
                const startIndex = contentStr.indexOf(startMarker);
                const endIndex = contentStr.indexOf(endMarker);
                
                if (startIndex === -1 || endIndex === -1) {
                    console.error('Could not find verification markers');
                    resolve({
                        isValid: false,
                        reason: 'PDF does not contain valid verification markers. This may not be a quiz report generated by our system.',
                        details: 'Missing verification content markers'
                    });
                    return;
                }

                // Extract content between markers and clean it
                let contentToHash = contentStr
                    .substring(startIndex + startMarker.length, endIndex)
                    .replace(/\) Tj/g, '')           // Remove PDF text operators
                    .replace(/ET\n?BT\n?/g, '')      // Remove PDF block markers
                    .replace(/\/F\d+ \d+ Tf/g, '')   // Remove font commands
                    .replace(/\d+(\.\d+)? TL/g, '')  // Remove leading commands
                    .replace(/\d+(\.\d+)? \d+(\.\d+)? Td/g, '') // Remove positioning
                    .replace(/\(/g, '')              // Remove opening parentheses
                    .replace(/\)/g, '')              // Remove closing parentheses
                    .replace(/T\*\s*\d*\.?g/g, '')   // Remove T* and g commands
                    .replace(/\s+/g, '')             // Remove whitespace
                    .trim();

                // Try to extract just the JSON part
                const jsonMatch = contentToHash.match(/({.*})/);
                if (!jsonMatch) {
                    console.error('Could not find JSON content in:', contentToHash);
                    resolve({
                        isValid: false,
                        reason: 'PDF content could not be parsed as valid JSON data.',
                        details: 'Invalid JSON structure in verification content'
                    });
                    return;
                }

                contentToHash = jsonMatch[1];

                try {
                    // Verify it's valid JSON
                    const parsedContent = JSON.parse(contentToHash);
                    // console.log('Successfully parsed JSON:', parsedContent);
                } catch (error) {
                    console.error('Content after cleaning');
                    resolve({
                        isValid: false,
                        reason: 'PDF contains corrupted or invalid data structure.',
                        details: 'JSON parsing failed after content extraction'
                    });
                    return;
                }

                // After extracting JSON content
                try {
                    // Parse and normalize the content
                    const parsedContent = JSON.parse(contentToHash);
                    
                    // Normalize quiz titles
                    if (parsedContent.highScores) {
                        parsedContent.highScores = parsedContent.highScores.map(score => ({
                            ...score,
                            quizTitle: score.quizTitle.replace(/\s+/g, '')
                        }));
                    }
                    
                    // Re-stringify for hashing
                    contentToHash = JSON.stringify(parsedContent);
                    
                    // console.log('Successfully normalized JSON:', parsedContent);
                } catch (error) {
                    console.error('Content normalization failed:', error);
                    resolve({
                        isValid: false,
                        reason: 'PDF data normalization failed during verification process.',
                        details: 'Content normalization error'
                    });
                    return;
                }

                // Extract verification data
                const verificationSection = contentStr.slice(endIndex);
                const hashPattern = /Verification Code:[^(]*\(([A-Fa-f0-9]{16})\)/;
                const timestampPattern = /Generated:[^(]*\(([\d]{4}-[\d]{2}-[\d]{2}T[\d]{2}:[\d]{2}:[\d]{2}\.[\d]{3}Z)\)/;

                const hashMatch = verificationSection.match(hashPattern);
                const timestampMatch = verificationSection.match(timestampPattern);

                if (!hashMatch || !timestampMatch) {
                    console.error('Could not extract verification data');
                    resolve({
                        isValid: false,
                        reason: 'PDF is missing verification data (hash or timestamp).',
                        details: 'Verification metadata not found'
                    });
                    return;
                }

                const extractedHash = hashMatch[1];
                const timestamp = timestampMatch[1];
                
                // Compare with last generated content
                // compareWithLastGenerated(contentToHash, timestamp);
                
                // Generate hash using same method
                const computedHash = generateContentHash(contentToHash, timestamp);
                
                const isValid = extractedHash === computedHash;
                
                resolve({
                    isValid,
                    reason: isValid ? 
                        'PDF verification successful! This is a valid quiz report generated by our system.' :
                        'PDF verification failed. The content has been modified or corrupted.',
                    details: isValid ?
                        `Hash verification passed: ${extractedHash.substring(0, 8)}...` :
                        `Hash mismatch: Expected ${computedHash.substring(0, 8)}..., Found ${extractedHash.substring(0, 8)}...`,
                    timestamp: timestamp,
                    hash: extractedHash
                });
            } catch (error) {
                console.error('Verification error:', error);
                resolve({
                    isValid: false,
                    reason: 'An unexpected error occurred during PDF verification.',
                    details: error.message || 'Unknown verification error'
                });
            }
        };
        
        reader.readAsArrayBuffer(file);
    });
}

