format:
  titlepage-pdf:
    include-in-header:
      - text: |
          % Soft "DRAFT" watermark for unreleased volumes
          \usepackage{draftwatermark}
          \SetWatermarkText{DRAFT}
          \SetWatermarkScale{0.75}
          \SetWatermarkAngle{45}
          \SetWatermarkColor[gray]{0.94}
  pdf:
    include-in-header:
      - text: |
          % Soft "DRAFT" watermark for unreleased volumes
          \usepackage{draftwatermark}
          \SetWatermarkText{DRAFT}
          \SetWatermarkScale{0.75}
          \SetWatermarkAngle{45}
          \SetWatermarkColor[gray]{0.94}
