github: [profvjreddi]

custom:
  - "https://github.com/harvard-edge/cs249r_book"

name: "Support Global Access to Open-Source AI Education"
description: |
  This book was created to address the lack of open-source resources in machine learning *systems* education. While this project grew out of my course at Harvard University, it has evolved into something much broader.

  To continue developing and expanding this project as an open source collaborative project, we need support to hire staff and teaching assistants from around the world. As this project extends beyond traditional institutional boundaries, external sponsorship is crucial for its sustainability. By sponsoring this project, you'll be helping to maintain and grow this valuable open-source resource, enabling contributors from diverse backgrounds to participate and improve the content.

  **Get Involved:**  
  We welcome contributions from the community! If you're interested in helping out, check the guidelines [here](https://github.com/harvard-edge/cs249r_book). For any questions or feedback, feel free to email me directly or start a discussion thread on GitHub.

  **Contributors:**  
  A big thanks to everyone who’s helped make this book what it is! You can see the full list of individual contributors [here](https://github.com/harvard-edge/cs249r_book/graphs/contributors).

thank_you_message: |
  Thank you for your support! Your contribution helps keep this project open-source and accessible to learners around the world.
  
contact: |
  If you have any questions or would like to discuss custom sponsorships, please reach out to [your-email@example.com].
