# =============================================================================
# PR LABELER CONFIGURATION
# =============================================================================
# Used by actions/labeler to auto-label PRs based on changed file paths.
# This is a fast fallback - the LLM labeler handles more complex cases.
# =============================================================================

# Project labels based on file paths
book:
  - changed-files:
      - any-glob-to-any-file:
          - 'book/**'
          - '*.qmd'

tinytorch:
  - changed-files:
      - any-glob-to-any-file:
          - 'tinytorch/**'

kits:
  - changed-files:
      - any-glob-to-any-file:
          - 'kits/**'

labs:
  - changed-files:
      - any-glob-to-any-file:
          - 'labs/**'

# Type labels based on common patterns
docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - '**/*.qmd'
          - '**/README*'
          - 'docs/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '*.yml'
          - '*.yaml'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '**/requirements*.txt'
          - '**/pyproject.toml'
          - '**/setup.py'
          - '**/package.json'
