/**
 * Dynamic StaffML corpus statistics.
 *
 * Single source of truth for every user-visible "we have N questions across
 * M topics" number in the app. Derived at build time from
 * `src/data/vault-manifest.json`, which is regenerated by
 * `scripts/generate-manifest.py` whenever the corpus changes.
 *
 * If you find yourself typing a number like "8,053" or "79" into a component,
 * stop and import from here instead. The one and only reason copy like "4,800+
 * questions" ever appeared in the codebase was that the manifest lived in a
 * different file from the metadata that referenced it. This module closes that
 * gap permanently.
 */
import manifest from "@/data/vault-manifest.json";

// ─── Raw counts (numbers) ────────────────────────────────────
export const QUESTION_COUNT: number = manifest.questionCount;
export const TOPIC_COUNT: number = manifest.conceptCount;
export const AREA_COUNT: number = manifest.areaCount;

/**
 * Deployment tracks surfaced in the primary UI. The manifest's
 * trackDistribution also contains a "global" bucket for cross-track questions;
 * that is NOT a deployment track, so we exclude it from the public-facing
 * count. The four user-facing tracks are Cloud / Edge / Mobile / TinyML.
 */
const EXCLUDED_TRACK_KEYS = new Set(["global"]);
export const TRACK_COUNT: number = Object.keys(manifest.trackDistribution).filter(
  (k) => !EXCLUDED_TRACK_KEYS.has(k),
).length;

/** Bloom-aligned difficulty levels: L1, L2, L3, L4, L5, L6+ */
export const LEVEL_COUNT: number = Object.keys(manifest.levelDistribution).length;

// ─── Formatted strings (pre-formatted for copy) ──────────────
const intFormatter = new Intl.NumberFormat("en-US");

/** "8,053" — use this in all user-visible copy. */
export const QUESTION_COUNT_FORMATTED: string = intFormatter.format(QUESTION_COUNT);

/** "79" — for consistency with the formatter even though it fits in two digits. */
export const TOPIC_COUNT_FORMATTED: string = intFormatter.format(TOPIC_COUNT);

// ─── Build metadata (strings) ────────────────────────────────
export const VERSION: string = manifest.version;
export const TAXONOMY_VERSION: string = manifest.taxonomyVersion;
export const BUILD_DATE: string = manifest.buildDate;
export const CONTENT_HASH: string = manifest.contentHash;

// ─── Distributions (for charts and the radar widget) ─────────
export const TRACK_DISTRIBUTION = manifest.trackDistribution;
export const LEVEL_DISTRIBUTION = manifest.levelDistribution;

// ─── Canned copy fragments (the three strings that used to be hardcoded) ───
/**
 * Pre-assembled social/meta description line. This is what shows on Twitter,
 * LinkedIn, and SEO cards. Keep it short and accurate; it gets cached by
 * crawlers and takes a while to refresh once wrong.
 */
export const SOCIAL_DESCRIPTION = `Physics-grounded ML systems interview prep. ${QUESTION_COUNT_FORMATTED} questions across cloud, edge, mobile, and TinyML. Free, open source, runs entirely in your browser.`;

export const SOCIAL_DESCRIPTION_LONG = `${QUESTION_COUNT_FORMATTED} physics-grounded ML systems questions with napkin math verification. Free, open source, no accounts, runs entirely in your browser.`;

export const SOCIAL_IMAGE_ALT = `StaffML — ${QUESTION_COUNT_FORMATTED} ML systems interview questions`;
