# =============================================================================
# EPUB CONFIGURATION
# =============================================================================
# This configuration is optimized for a professional ePub book output.
#
# Key Features:
# - Standard e-book format with clean, reflowable text
# - Full support for e-reader navigation and table of contents
# - Includes all necessary metadata for distribution (Dublin Core)
# - Follows the same chapter structure as the PDF and HTML versions
#
# Usage:
#   make build-epub     # Uses this config automatically
#   make preview-epub   # Uses this config for ePub development
# =============================================================================

project:
  type: book
  output-dir: _build/epub
  post-render:
    - scripts/clean_svgs.py

  preview:
    browser: false
    navigate: false

book:
  favicon: assets/images/icons/favicon.png
  cover-image: assets/images/covers/cover-hardcover-book.png
  cover-image-alt: "Cover image."

  title: "Machine Learning Systems"
  subtitle: "Principles and Practices of Engineering Artificially Intelligent Systems"

  date: today
  date-format: long

  author:
    name: "Prof. Vijay Janapa Reddi"
    email: vj@eecs.harvard.edu
    url: https://www.google.com/search?q=Vijay+Janapa+Reddi
    affiliations: 
      - name: "Harvard University"
        department: "School of Engineering and Applied Sciences"
        city: "Cambridge"
        state: "MA"
        country: "USA"
    corresponding: true
    roles: "Author, editor and curator."
    orcid: "0000-0002-5259-7721"
    
  # Additional publication metadata (when available)
  # publisher: "Harvard University"
  # publisher-place: "Cambridge, MA"  
  # isbn: "978-0-XXX-XXXXX-X"
  # doi: "10.XXXX/mlsysbook"

  abstract: |
    Machine Learning Systems presents a comprehensive approach to understanding and engineering machine learning (ML). While many resources focus on ML algorithms and model architectures, this book serves as a bridge between theoretical foundations and practical engineering. It emphasizes the systems context that engineers need to master when building AI solutions in the real world. The text progresses from foundational concepts to advanced system design, integrating topics such as data engineering, model optimization, hardware-aware training approaches, and inference acceleration strategies. Throughout the book, readers develop a principled understanding of ML systems engineering, learning to reason about system architectures and address critical challenges in areas including security, privacy, and reliability. While ML applications and tools evolve rapidly, the engineering principles for building ML systems remain largely consistent. This book distills these enduring concepts, making it a resource for anyone seeking to build flexible, efficient, and robust ML systems.

    ----

    :::: {.content-visible when-format="html"}
    🎙 Listen to the **AI Podcast**,
    created using Google's Notebook LM and inspired by insights drawn from our
    [IEEE education viewpoint paper](https://web.eng.fiu.edu/gaquan/Papers/ESWEEK24Papers/CPS-Proceedings/pdfs/CODES-ISSS/563900a043/563900a043.pdf).
    This podcast provides an accessible overview of what this book is all about.

    &nbsp;
    <audio controls="controls">
      <source src="assets/media/notebooklm_podcast_mlsysbookai.mp3" type="audio/mpeg" />
      Your reader does not support audio.
    </audio>
    ::::

    ----

  repo-url: https://github.com/harvard-edge/cs249r_book

  page-footer:
    left: |
      Written, edited and curated by Prof. Vijay Janapa Reddi (Harvard University)
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  chapters:
    - index.qmd
    
    # Frontmatter
    - contents/frontmatter/foreword.qmd
    - contents/frontmatter/about/about.qmd
    - contents/frontmatter/changelog/changelog.qmd
    - contents/frontmatter/acknowledgements/acknowledgements.qmd
    - contents/frontmatter/socratiq/socratiq.qmd
    
    # Part I: Foundations
    - part: contents/parts/foundations.qmd
      chapters:
        - contents/core/introduction/introduction.qmd
        - contents/core/ml_systems/ml_systems.qmd
        - contents/core/dl_primer/dl_primer.qmd
        - contents/core/dnn_architectures/dnn_architectures.qmd
    
    # Part II: Design Principles  
    - part: contents/parts/design_principles.qmd
      chapters:
        - contents/core/workflow/workflow.qmd
        - contents/core/data_engineering/data_engineering.qmd
        - contents/core/frameworks/frameworks.qmd
        - contents/core/training/training.qmd
    
    # Part III: Performance Engineering
    - part: "Performance Engineering"
      chapters:
        - contents/core/efficient_ai/efficient_ai.qmd
        - contents/core/optimizations/optimizations.qmd
        - contents/core/hw_acceleration/hw_acceleration.qmd
        - contents/core/benchmarking/benchmarking.qmd
    
    # Part IV: Robust Deployment
    - part: "Robust Deployment"
      chapters:
        - contents/core/ops/ops.qmd
        - contents/core/ondevice_learning/ondevice_learning.qmd
        - contents/core/robust_ai/robust_ai.qmd
        - contents/core/privacy_security/privacy_security.qmd
    
    # Part V: Trustworthy Systems
    - part: contents/parts/best_practices.qmd
      chapters:
        - contents/core/responsible_ai/responsible_ai.qmd
        - contents/core/sustainable_ai/sustainable_ai.qmd
        - contents/core/ai_for_good/ai_for_good.qmd
    
    # Part VI: Frontiers
    - part: "Frontiers"
      chapters:
        - contents/core/conclusion/conclusion.qmd
    
    # Part VII: Laboratory Exercises
    - part: "Hands-on Labs"
      chapters:
        - contents/labs/labs.qmd
        - contents/labs/kits.qmd
        - contents/labs/ide_setup.qmd
    
    # Part VIII: Arduino Labs
    - part: "Arduino Labs"
      chapters:
        - contents/labs/arduino/nicla_vision/nicla_vision.qmd
        - contents/labs/arduino/nicla_vision/setup/setup.qmd
        - contents/labs/arduino/nicla_vision/image_classification/image_classification.qmd
        - contents/labs/arduino/nicla_vision/object_detection/object_detection.qmd
        - contents/labs/arduino/nicla_vision/kws/kws.qmd
        - contents/labs/arduino/nicla_vision/motion_classification/motion_classification.qmd
    
    # Part IX: Seeed XIAO ESP32S3 Labs
    - part: "Seeed XIAO ESP32S3 Labs"
      chapters:
        - contents/labs/seeed/xiao_esp32s3/xiao_esp32s3.qmd
        - contents/labs/seeed/xiao_esp32s3/setup/setup.qmd
        - contents/labs/seeed/xiao_esp32s3/image_classification/image_classification.qmd
        - contents/labs/seeed/xiao_esp32s3/object_detection/object_detection.qmd
        - contents/labs/seeed/xiao_esp32s3/kws/kws.qmd
        - contents/labs/seeed/xiao_esp32s3/motion_classification/motion_classification.qmd
    
    # Part X: Grove Vision Labs
    - part: "Grove Vision AI V2 Labs"
      chapters:
        - contents/labs/seeed/grove_vision_ai_v2/grove_vision_ai_v2.qmd
        - contents/labs/seeed/grove_vision_ai_v2/setup_and_no_code_apps/setup_and_no_code_apps.qmd
        - contents/labs/seeed/grove_vision_ai_v2/image_classification/image_classification.qmd
        - contents/labs/seeed/grove_vision_ai_v2/object_detection/object_detection.qmd
    
    # Part XI: Raspberry Pi Labs
    - part: "Raspberry Pi Labs"
      chapters:
        - contents/labs/raspi/raspi.qmd
        - contents/labs/raspi/setup/setup.qmd
        - contents/labs/raspi/image_classification/image_classification.qmd
        - contents/labs/raspi/object_detection/object_detection.qmd
        - contents/labs/raspi/llm/llm.qmd
        - contents/labs/raspi/vlm/vlm.qmd
    
    # Part XII: Shared Labs
    - part: "Shared Labs"
      chapters:
        - contents/labs/shared/shared.qmd
        - contents/labs/shared/kws_feature_eng/kws_feature_eng.qmd
        - contents/labs/shared/dsp_spectral_features_block/dsp_spectral_features_block.qmd
    
    # Backmatter
    - contents/backmatter/references.qmd

bibliography:
  - contents/core/introduction/introduction.bib
  - contents/core/ai_for_good/ai_for_good.bib
  - contents/core/benchmarking/benchmarking.bib
  - contents/core/data_engineering/data_engineering.bib
  - contents/core/dl_primer/dl_primer.bib
  - contents/core/dnn_architectures/dnn_architectures.bib
  - contents/core/efficient_ai/efficient_ai.bib
  - contents/core/ml_systems/ml_systems.bib
  - contents/core/frameworks/frameworks.bib
  - contents/core/hw_acceleration/hw_acceleration.bib
  - contents/core/ondevice_learning/ondevice_learning.bib
  - contents/core/ops/ops.bib
  - contents/core/optimizations/optimizations.bib
  - contents/core/privacy_security/privacy_security.bib
  - contents/core/responsible_ai/responsible_ai.bib
  - contents/core/robust_ai/robust_ai.bib
  - contents/core/sustainable_ai/sustainable_ai.bib
  - contents/core/training/training.bib
  - contents/core/workflow/workflow.bib
  - contents/core/conclusion/conclusion.bib

filters:
  #- filters/sidenote.lua
  #- filters/inject_parts.lua
  #- filters/inject_quizzes.lua
  - pandoc-ext/diagram
  #- filters/inject_crossrefs.lua    # This must come before custom-numbered-blocks (relies on \ref{...})
  - mlsysbook-ext/custom-numbered-blocks
  #- mlsysbook-ext/margin-video
  #- filters/margin-connections.lua  # This filter must come after custom-numbered-blocks

# Filter configurations and metadata
filter-metadata:
  # Quiz configuration for inject_quizzes.lua filter
  quiz-config:
    file-pattern: "*_quizzes.json"          # Pattern for quiz file discovery in PDF builds
    scan-directory: "contents/core"         # Directory to scan for quiz files
    auto-discover-pdf: true                 # Whether to enable auto-discovery in PDF builds

  # Cross-reference injection configuration for inject_crossrefs.lua filter  
  cross-references:
    file: "data/cross_refs_final.json"      # Path to cross-references JSON file
    enabled: true                           # Enable/disable cross-reference injection

  # Part summaries injection configuration for inject_parts.lua filter
  part-summaries:
    file: "data/part_summaries.yml"              # Path to part summaries YAML file
    enabled: true                           # Enable/disable part summary injection

  # Custom numbered blocks configuration for mlsysbook-ext/custom-numbered-blocks filter
  mlsysbook-ext/custom-numbered-blocks:
    icon-path: "assets/images/icons/callouts"  # Path to callout icons
    icon-format: "png"                         # Icon format for ePub builds
    groups:
      quiz-question:
        colors: ["F0F0F8", "5B4B8A"]  # Darker purple for quiz questions
        collapse: false
      quiz-answer:
        colors: ["E8F2EA", "4a7c59"]  # Forest green for quiz answers
        collapse: true
      definition:
        colors: ["F0F8FF", "4682B4"]  # Alice blue background, steel blue border for definitions
        collapse: false
        numbered: false
      example:
        colors: ["F8F9FA", "6C757D"]  # Light gray background, medium gray border for examples
        collapse: false
        numbered: false
    classes:
      callout-quiz-question: 
        label: "Self-Check: Question"
        group: quiz-question
      callout-quiz-answer:
        label: "Self-Check: Answer"
        group: quiz-answer
      callout-definition:
        label: "Definition"
        group: definition
      callout-example:
        label: "Example"
        group: example

diagram:
  engine:
    dot: false
    mermaid: false
    asymptote: false
    tikz:
      execpath: lualatex
      header-includes:
        - '\usepackage{tikz}'
        - '\usepackage{pgfplots}'
        - '\usepackage{pgf-pie}'
        - '\usepackage{amsmath}'
        - '\usepackage{amssymb}'
        - '\usepackage{xcolor}'
        - '\pgfplotsset{compat=1.9}'
        - '\usepgfplotslibrary{fillbetween}'      
        - '\usetikzlibrary{angles}'
        - '\usetikzlibrary{arrows.meta}'
        - '\usetikzlibrary{arrows}'
        - '\usetikzlibrary{backgrounds}'
        - '\usetikzlibrary{bending}'
        - '\usetikzlibrary{calc}'
        - '\usetikzlibrary{fit}'
        - '\usetikzlibrary{intersections}'
        - '\usetikzlibrary{positioning}'
        - '\usetikzlibrary{shapes.geometric}'
        - '\usetikzlibrary{shapes}'
        - '\usetikzlibrary{quotes}'
        - '\usetikzlibrary{decorations.pathmorphing}'
        - '\usetikzlibrary{decorations.markings}'
        - '\usetikzlibrary{matrix}'
        - '\usepgfplotslibrary{dateplot}'
        - '\usepgfplotslibrary{polar}'
        - '\definecolor{Brown}{rgb}{0.65, 0.16, 0.16}'
        - '\definecolor{BrownL}{rgb}{0.6, 0.4, 0.2}'
        - '\definecolor{BrownLine}{rgb}{0.5, 0.3, 0.1}'
        - '\definecolor{BackColor}{RGB}{255,255,229}'
        - '\definecolor{BackLine}{RGB}{181,181,72}'
        - '\definecolor{BlueD}{RGB}{62,100,125}'
        - '\definecolor{BlueL}{RGB}{209,243,255}'
        - '\definecolor{BlueLine}{RGB}{34,148,189}'
        - '\definecolor{BrownL}{RGB}{233,222,220}'
        - '\definecolor{BrownLine}{RGB}{143,120,116}'
        - '\definecolor{Green}{rgb}{0.0, 0.5, 0.0}'
        - '\definecolor{GreenD}{RGB}{40,117,40}'
        - '\definecolor{GreenL}{RGB}{219,253,166}'
        - '\definecolor{GreenLine}{RGB}{73,89,56}'
        - '\definecolor{OliveL}{RGB}{230,227,191}'
        - '\definecolor{OliveLine}{RGB}{173,166,10}'
        - '\definecolor{OrangeL}{RGB}{250,212,175}'
        - '\definecolor{OrangeLine}{RGB}{255,127,76}'
        - '\definecolor{RedL}{RGB}{253,226,240}'
        - '\definecolor{RedLine}{RGB}{201,20,110}'
        - '\definecolor{Sepia}{rgb}{0.44, 0.26, 0.08}'
        - '\definecolor{TextColor}{RGB}{224,224,224}'
        - '\definecolor{VioletL}{RGB}{247,180,247}'
        - '\definecolor{VioletL2}{RGB}{243,243,255}'
        - '\definecolor{VioletLine}{RGB}{34,125,189}'
        - '\definecolor{VioletLine2}{RGB}{169,136,229}'

editor:
  render-on-save: true

format:
  epub:
    # --- EPUB-Specific Settings ---
    language: "en-US"
    
    # --- Dublin Core Metadata (EPUB-specific) ---
    identifier: "https://mlsysbook.ai/epub"
    contributor: "Harvard University, School of Engineering and Applied Sciences"
    subject: "Machine Learning, Computer Science, Engineering, Artificial Intelligence, Systems Design"
    description: "A textbook on machine learning systems engineering, covering principles and practices for building AI solutions in real-world environments."
    
    # --- Additional EPUB Metadata ---
    type: "Text"
    format: "application/epub+zip"
    source: "https://mlsysbook.ai"
    relation: "https://mlsysbook.ai"
    coverage: "Global"

    # --- Table of Contents & Navigation ---
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    
    # --- Content Structure & Layout ---
    epub-chapter-level: 1
    epub-cover-image: "assets/images/covers/cover_image_title.png"
    epub-title-page: true

    # --- Styling and Formatting ---
    css: "assets/styles/epub.css"
    code-overflow: wrap
    code-copy: true
    code-line-numbers: true
    
    # --- Section Numbering ---
    number-sections: false
    number-depth: 3
    
    # --- Figures & Tables ---
    fig-align: center
    fig-caption: true
    
    # --- Footnotes ---
    footnotes-hover: true
    link-citations: true
    citations-hover: true

resources:
  - CNAME
  - assets
