# ╔═══════════════════════════════════════════════════════════════════════════════╗
# ║                        🚨 CRITICAL WARNING 🚨                                ║
# ║                     AUTOGENERATED! DO NOT EDIT!                              ║
# ║                                                                               ║
# ║  This file is AUTOMATICALLY GENERATED from source modules.                   ║
# ║  ANY CHANGES MADE HERE WILL BE LOST when modules are re-exported!            ║
# ║                                                                               ║
# ║  ✅ TO EDIT: src/XX_transformer/XX_transformer.py                   ║
# ║  ✅ TO EXPORT: Run 'tito dev export' (src/) or 'tito module complete XX'     ║
# ║                                                                               ║
# ║  🛡️ STUDENT PROTECTION: This file contains optimized implementations.        ║
# ║     Editing it directly may break module functionality and training.         ║
# ║                                                                               ║
# ║  🎓 LEARNING TIP: Work in src/ (developers) or modules/ (learners)           ║
# ║     The tinytorch/ directory is generated code - edit source files instead!  ║
# ╚═══════════════════════════════════════════════════════════════════════════════╝
"""
TinyTorch Models: Transformer (GPT)
===================================

Canonical Generative Pretrained Transformer architecture, assembled from
TinyTorch LEGO bricks:
  - EmbeddingLayer (tinytorch.core.embeddings)
  - TransformerBlock, LayerNorm, create_causal_mask, sample_next_token, generate (tinytorch.core.transformers)
  - Linear (tinytorch.core.layers)
"""

from typing import Any, List, Optional
import numpy as np

from tinytorch.core.tensor import Tensor
from tinytorch.core.layers import Linear
from tinytorch.core.embeddings import EmbeddingLayer
from tinytorch.core.transformers import (
    LayerNorm,
    TransformerBlock,
    create_causal_mask,
    sample_next_token,
    generate,
)

rng = np.random.default_rng(7)


class GPT:
    """
    Complete GPT (Generative Pre-trained Transformer) model.

    Assembled from TinyTorch LEGO bricks:
    tokens → EmbeddingLayer → TransformerBlock × N → LayerNorm → Linear (LM Head)
    """

    def __init__(
        self,
        vocab_size: int,
        embed_dim: int,
        num_layers: int,
        num_heads: int,
        max_seq_len: int = 1024,
    ):
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.num_layers = num_layers
        self.num_heads = num_heads
        self.max_seq_len = max_seq_len

        # Embedding layer (Token + Learned Positional)
        self.embedding_layer = EmbeddingLayer(vocab_size, embed_dim, max_seq_len)

        # Stack of transformer blocks
        self.blocks = [
            TransformerBlock(embed_dim, num_heads) for _ in range(num_layers)
        ]

        # Final layer normalization
        self.ln_f = LayerNorm(embed_dim)

        # Language modeling head (projects to vocabulary)
        self.lm_head = Linear(embed_dim, vocab_size, bias=False)

    def forward(self, tokens: Tensor, start_pos: int = 0) -> Tensor:
        """Forward pass through GPT model."""
        batch_size, seq_len = tokens.shape

        # Token + positional embeddings
        x = self.embedding_layer.forward(tokens, start_pos)

        # Causal mask for autoregressive routing
        mask = create_causal_mask(seq_len)

        # Transformer blocks
        for block in self.blocks:
            x = block.forward(x, mask)

        # Final LayerNorm & LM Head projection
        x = self.ln_f.forward(x)
        logits = self.lm_head.forward(x)

        return logits

    def __call__(self, tokens: Tensor, start_pos: int = 0) -> Tensor:
        return self.forward(tokens, start_pos)

    def _create_causal_mask(self, seq_len: int) -> Tensor:
        return create_causal_mask(seq_len)

    def _sample_next_token(self, logits: np.ndarray, temperature: float = 1.0) -> int:
        return sample_next_token(logits, temperature, rng=rng)

    def generate(
        self,
        prompt_tokens: Tensor,
        max_new_tokens: int = 50,
        temperature: float = 1.0,
    ) -> Tensor:
        """Autoregressively generate tokens using the decoupled generate utility."""
        return generate(
            self,
            prompt_tokens,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            max_seq_len=self.max_seq_len,
            rng=rng,
        )

    def parameters(self) -> List[Tensor]:
        """Return all learnable parameters."""
        params = []
        params.extend(self.embedding_layer.parameters())
        for block in self.blocks:
            params.extend(block.parameters())
        params.extend(self.ln_f.parameters())
        params.extend(self.lm_head.parameters())
        return params


TinyGPT = GPT

__all__ = ["GPT", "TinyGPT"]
