# Hand-maintained reference model. This file is NOT generated by `tito dev
# export`; it is tracked in git and edited directly here.
#
# It assembles the reference GPT (aliased TinyGPT) from the building blocks
# students export in Modules 11-13 (EmbeddingLayer, LayerNorm, TransformerBlock,
# create_causal_mask, sample_next_token, generate) plus Module 03's Linear.
# Module 13 re-exports GPT/TinyGPT from here, so `tinytorch.core.transformers.GPT`
# (used by Milestone 06) resolves to this class. Module 13's own notebook tests
# build GPT from the notebook's classes by passing them in (block_cls=...), so
# they run before Module 13 is exported. Keep its interface in step with
# src/13_transformers/13_transformers.py.
"""
TinyTorch Models: Transformer (GPT)
===================================

Canonical Generative Pretrained Transformer architecture, assembled from
TinyTorch LEGO bricks:
  - EmbeddingLayer (tinytorch.core.embeddings)
  - TransformerBlock, LayerNorm, create_causal_mask, sample_next_token, generate (tinytorch.core.transformers)
  - Linear (tinytorch.core.layers)
"""

from typing import Any, Callable, List, Optional
import numpy as np

from tinytorch.core.tensor import Tensor
from tinytorch.core.layers import Linear
from tinytorch.core.embeddings import EmbeddingLayer


def _exported(name: str) -> Any:
    """One Module 13 building block from the student's exported package.

    Imported at GPT construction, not at the top of this file, because
    tinytorch.core.transformers re-exports GPT from here and an eager import
    would be circular. There is deliberately no other default source: an
    earlier fallback read the blocks from ``__main__``, which let a script's
    own definitions stand in for the student's exported Module 13.
    """
    try:
        from tinytorch.core import transformers as _tf
    except ImportError:
        _tf = None
    component = getattr(_tf, name, None)
    if component is None:
        raise ImportError(
            f"GPT needs {name} from YOUR exported Module 13 (tinytorch.core.transformers); "
            "run `tito module complete 13` first, or pass it to GPT explicitly."
        )
    return component


rng = np.random.default_rng(7)


class GPT:
    """
    Complete GPT (Generative Pre-trained Transformer) model.

    Assembled from TinyTorch LEGO bricks:
    tokens → EmbeddingLayer → TransformerBlock × N → LayerNorm → Linear (LM Head)

    The Module 13 pieces default to the exported tinytorch.core.transformers.
    Pass them explicitly (block_cls, norm_cls, mask_fn, sample_fn, generate_fn)
    to assemble GPT from other definitions, as Module 13's notebook does to test
    its own classes before they are exported.
    """

    def __init__(
        self,
        vocab_size: int,
        embed_dim: int,
        num_layers: int,
        num_heads: int,
        max_seq_len: int = 1024,
        *,
        block_cls: Optional[type] = None,
        norm_cls: Optional[type] = None,
        mask_fn: Optional[Callable] = None,
        sample_fn: Optional[Callable] = None,
        generate_fn: Optional[Callable] = None,
    ):
        block_cls = block_cls or _exported("TransformerBlock")
        norm_cls = norm_cls or _exported("LayerNorm")
        self._mask_fn = mask_fn or _exported("create_causal_mask")
        self._sample_fn = sample_fn or _exported("sample_next_token")
        self._generate_fn = generate_fn or _exported("generate")

        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.num_layers = num_layers
        self.num_heads = num_heads
        self.max_seq_len = max_seq_len

        # Embedding layer (Token + Learned Positional)
        self.embedding_layer = EmbeddingLayer(vocab_size, embed_dim, max_seq_len)

        # Stack of transformer blocks
        self.blocks = [
            block_cls(embed_dim, num_heads) for _ in range(num_layers)
        ]

        # Final layer normalization
        self.ln_f = norm_cls(embed_dim)

        # Language modeling head (projects to vocabulary)
        self.lm_head = Linear(embed_dim, vocab_size, bias=False)

    def forward(self, tokens: Tensor, start_pos: int = 0) -> Tensor:
        """Forward pass through GPT model."""
        batch_size, seq_len = tokens.shape

        # Token + positional embeddings
        x = self.embedding_layer.forward(tokens, start_pos)

        # Causal mask for autoregressive routing
        mask = self._mask_fn(seq_len)

        # Transformer blocks
        for block in self.blocks:
            x = block.forward(x, mask)

        # Final LayerNorm & LM Head projection
        x = self.ln_f.forward(x)
        logits = self.lm_head.forward(x)

        return logits

    def __call__(self, tokens: Tensor, start_pos: int = 0) -> Tensor:
        return self.forward(tokens, start_pos)

    def _create_causal_mask(self, seq_len: int) -> Tensor:
        return self._mask_fn(seq_len)

    def _sample_next_token(self, logits: np.ndarray, temperature: float = 1.0) -> int:
        return self._sample_fn(logits, temperature, rng=rng)

    def generate(
        self,
        prompt_tokens: Tensor,
        max_new_tokens: int = 50,
        temperature: float = 1.0,
    ) -> Tensor:
        """Autoregressively generate tokens using the decoupled generate utility."""
        return self._generate_fn(
            self,
            prompt_tokens,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            max_seq_len=self.max_seq_len,
            rng=rng,
        )

    def parameters(self) -> List[Tensor]:
        """Return all learnable parameters."""
        params = []
        params.extend(self.embedding_layer.parameters())
        for block in self.blocks:
            params.extend(block.parameters())
        params.extend(self.ln_f.parameters())
        params.extend(self.lm_head.parameters())
        return params


TinyGPT = GPT

__all__ = ["GPT", "TinyGPT"]
