#!/usr/bin/env python3
"""Regenerate JOURNAL.md chapter table from chapters/*.status.yaml (parallel-safe)."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None  # type: ignore

ROOT = Path(__file__).resolve().parent / "artifacts" / "lego_unit_migration"
CHAPTERS_DIR = ROOT / "chapters"
JOURNAL = ROOT / "JOURNAL.md"

# Static rows preserved at top of JOURNAL (phase table + header); chapter rows regenerated.
PHASE_TABLE = """| Phase | Status | Commit SHA | Notes |
|-------|--------|------------|-------|
| P0 foundation | done | 3bb5d63–3250400 | fmt_qty, linters, journal |
| vol2 prose-units | done | 14fd7a535a | 14 files, 0 violations |
| Corpus equations | done | — | green |
| Corpus prose-units | done | 14fd7a535a | vol1 + vol2 |
"""


def load_status_files() -> list[dict]:
    rows: list[dict] = []
    for path in sorted(CHAPTERS_DIR.glob("*.status.yaml")):
        text = path.read_text(encoding="utf-8")
        if yaml is not None:
            data = yaml.safe_load(text) or {}
        else:
            # minimal fallback: chapter + commit lines only
            data = {}
            for line in text.splitlines():
                if ":" in line:
                    k, v = line.split(":", 1)
                    data[k.strip()] = v.strip().strip('"')
        data["_path"] = path.name
        rows.append(data)
    return rows


def signoff_emoji(row: dict) -> str:
    if row.get("sign_off") in (True, "true", "yes"):
        return "✅"
    if row.get("blocker"):
        return "⛔"
    if row.get("llm") == "PASS" and row.get("html") == "PASS":
        return "🔄"
    return "⬜"


def format_row(row: dict) -> str:
    ch = row.get("chapter", row.get("_path", "?"))
    llm = row.get("llm", "—")
    if row.get("cells_audit"):
        steps = f"✓ {row['cells_audit']}"
    elif row.get("cells"):
        steps = f"cells {row['cells']}"
    else:
        steps = "—"
    commit = row.get("commit") or row.get("notes") or "—"
    if commit in (None, "null", ""):
        commit = row.get("blocker") or "pending"
    return f"| {ch} | {llm} | {steps} | {signoff_emoji(row)} | {commit} |"


def build_chapter_section(rows: list[dict]) -> str:
    signed = sum(1 for r in rows if r.get("sign_off") in (True, "true", "yes"))
    lines = [
        "## Chapters (14-step gate)",
        "",
        "_Regenerated by `book/tools/audit/sync_lego_journal.py` from `chapters/*.status.yaml`._",
        "",
        "| Chapter | Step 11 LLM | Steps 8–10 | Sign-off | Commit |",
        "|---------|-------------|------------|----------|--------|",
    ]
    for row in rows:
        lines.append(format_row(row))
    lines.extend(
        [
            "",
            f"**Signed off (from status files):** {signed} / {len(rows)} status files",
            f"**Synced:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
        ]
    )
    return "\n".join(lines)


def merge_journal(chapter_section: str) -> None:
    if JOURNAL.exists():
        text = JOURNAL.read_text(encoding="utf-8")
        # Replace chapter section or append
        if "## Chapters (14-step gate)" in text:
            text = re.sub(
                r"## Chapters \(14-step gate\).*?(?=\n## |\Z)",
                chapter_section + "\n",
                text,
                flags=re.DOTALL,
            )
        else:
            text = text.rstrip() + "\n\n" + chapter_section
    else:
        text = "# LEGO Unit Migration Journal\n\n" + PHASE_TABLE + "\n\n" + chapter_section

    # Merge pending lessons if present
    lessons_pending = CHAPTERS_DIR / "_lessons_pending.md"
    if lessons_pending.exists():
        block = lessons_pending.read_text(encoding="utf-8").strip()
        if block and "## Pending lessons" not in text:
            text = text.rstrip() + "\n\n## Pending lessons (→ PLAYBOOK)\n\n" + block + "\n"

    JOURNAL.write_text(text, encoding="utf-8")
    print(f"Updated {JOURNAL}")


def main() -> int:
    rows = load_status_files()
    if not rows:
        print("No chapters/*.status.yaml found; JOURNAL chapter table unchanged.")
        return 0
    merge_journal(build_chapter_section(rows))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
