"""Shared helpers for MLSysBook interactive trade-off labs."""

from .legacy_components import (
    Card,
    ComparisonRow,
    DecisionLog,
    FailureBanner,
    LatencyWaterfall,
    MathPeek,
    MetricRow,
    PredictionLock,
    RooflineVisualizer,
    StakeholderMessage,
)
from .catalog import LAB_CATALOG, get_lab_metadata
from .reports import build_lab_report, report_export, report_export_panel, report_text_fallback
from .registry_refs import resolve_mlsysim_ref
from .schemas import (
    DEFAULT_TRACKS,
    ChapterRecap,
    InstructorMetadata,
    LabTrackVariant,
    LabMetadata,
    LabReport,
    LedgerEntry,
    NuggetSpec,
    TrackProfile,
    TrackSpec,
)
from .state import DesignLedger, LedgerState
from .style import ACADEMIC_LAB_CSS, COLORS, LAB_CSS, apply_plotly_theme
from .tracks import (
    CANONICAL_TRACKS,
    DEFAULT_TRACK_ID,
    TRACK_ALIASES,
    get_track_profile,
    normalize_track_id,
    track_options,
    track_profile_map,
)
from .ui import (
    COMPLETION_STATES,
    advanced_knob_drawer,
    big_takeaways,
    chapter_recap,
    checkpoint_card,
    constraint_check,
    decision_card,
    evidence_summary,
    instructor_adoption_card,
    lab_map,
    lab_header,
    learning_objectives,
    micro_brief,
    nugget_shell,
    part_header,
    reflection_card,
    scenario_brief,
    scenario_slice,
    source_trace,
    track_context,
    track_selector,
    what_you_need_to_know,
)
from .variants import (
    LAB_TRACK_VARIANTS,
    PILOT_LAB_IDS,
    canonical_track_ids,
    get_lab_track_variant,
    list_lab_variants,
    variant_coverage,
)
from .versions import LEDGER_SCHEMA_VERSION, MLSYSBOOK_LABS_VERSION, REPORT_SCHEMA_VERSION, STABLE_RELEASE_CHANNEL

__all__ = [
    "ACADEMIC_LAB_CSS",
    "COLORS",
    "LAB_CSS",
    "apply_plotly_theme",
    "DesignLedger",
    "LedgerState",
    "Card",
    "ComparisonRow",
    "DecisionLog",
    "FailureBanner",
    "LatencyWaterfall",
    "MathPeek",
    "MetricRow",
    "PredictionLock",
    "RooflineVisualizer",
    "StakeholderMessage",
    "LabMetadata",
    "ChapterRecap",
    "TrackSpec",
    "TrackProfile",
    "LabTrackVariant",
    "NuggetSpec",
    "InstructorMetadata",
    "LedgerEntry",
    "LabReport",
    "LAB_CATALOG",
    "DEFAULT_TRACKS",
    "CANONICAL_TRACKS",
    "DEFAULT_TRACK_ID",
    "TRACK_ALIASES",
    "MLSYSBOOK_LABS_VERSION",
    "REPORT_SCHEMA_VERSION",
    "LEDGER_SCHEMA_VERSION",
    "STABLE_RELEASE_CHANNEL",
    "normalize_track_id",
    "get_track_profile",
    "track_options",
    "track_profile_map",
    "LAB_TRACK_VARIANTS",
    "PILOT_LAB_IDS",
    "canonical_track_ids",
    "get_lab_track_variant",
    "list_lab_variants",
    "variant_coverage",
    "COMPLETION_STATES",
    "lab_header",
    "learning_objectives",
    "chapter_recap",
    "scenario_brief",
    "lab_map",
    "track_selector",
    "track_context",
    "part_header",
    "what_you_need_to_know",
    "micro_brief",
    "scenario_slice",
    "nugget_shell",
    "constraint_check",
    "source_trace",
    "evidence_summary",
    "checkpoint_card",
    "big_takeaways",
    "advanced_knob_drawer",
    "reflection_card",
    "decision_card",
    "instructor_adoption_card",
    "build_lab_report",
    "report_export",
    "report_export_panel",
    "report_text_fallback",
    "get_lab_metadata",
    "resolve_mlsysim_ref",
]
