# Resources {#sec-resources}

Embarking on your TinyML journey has never been easier with the curated resources to pave your path to expertise. There are coding platforms and communities where you can immerse yourself in hands-on TinyML projects, sharing or seeking advice on GitHub and Stack Overflow. Meanwhile, there are gateways to structured learning featuring courses that provide a comprehensive education in the field.

While this page serves as a solid starting point, stay tuned as we continually expand our resource pool, with the aim to foster a rich learning and collaborative environment for TinyML enthusiasts of all levels.

## Books

Here is a list of recommended books for learning about TinyML or embedded AI:

1. [TinyML: Machine Learning with TensorFlow Lite on Arduino and Ultra-Low-Power Microcontrollers](https://www.amazon.com/TinyML-Learning-TensorFlow-Ultra-Low-Power-Microcontrollers/dp/1492052043) by Pete Warden and Daniel Situnayake

2. [AI at the Edge: Solving Real-World Problems with Embedded Machine Learning](https://www.oreilly.com/library/view/ai-at-the/9781098120191/) by Daniel Situnayake and Jenny Plunkett

3. [TinyML Cookbook: Combine artificial intelligence and ultra-low-power embedded devices to make the world smarter](https://www.amazon.com/TinyML-Cookbook-artificial-intelligence-ultra-low-power/dp/180181497X) by Gian Marco Iodice

4. [Introduction to TinyML](https://www.amazon.com/Introduction-TinyML-Rohit-Sharma/dp/B0B5Q281L9) by Rohit Sharma

5. [Integrated camera, microphone, BLE, Wi-Fi and the most compact design](https://mjrovai.github.io/XIAO_Big_Power_Small_Board-ebook/) by Lei Feng(Seeed Studio), Marcelo Rovai

These books cover a range of topics related to TinyML and embedded AI, including:

- The fundamentals of machine learning and TinyML
- How to choose the right hardware and software for your project
- How to train and deploy TinyML models on embedded devices
- Real-world examples of TinyML applications

In addition to the above books, there are a number of other resources available for learning about TinyML and embedded AI, including online courses, tutorials, and blog posts. Some of these are listed below. Another great way to learn is by joining the [community](./community.qmd) of embedded AI developers.

## Tutorials

## Frameworks

1. **GitHub** Description: There are various GitHub repositories dedicated to TinyML where you can contribute or learn from existing projects. Some popular organizations/repos to check out are:

- TensorFlow Lite Micro: [GitHub Repository](https://github.com/tensorflow/tflite-micro)
- TinyML4D: [GitHub Repository](https://tinyml.seas.harvard.edu/4D/)
- Edge Impulse Expert Network: [Repository](https://docs.edgeimpulse.com/experts/)

2. **Stack Overflow** Tags: [tinyml](https://stackoverflow.com/questions/tagged/tinyml) Description: Use the "tinyml" tag on Stack Overflow to ask technical questions and find answers from the community.

## Courses and Learning Platforms

1. **Coursera** Course: [Introduction to Embedded Machine Learning](https://www.coursera.org/learn/introduction-to-embedded-machine-learning) Description: A dedicated course on Coursera to learn the basics and advances of TinyML.

2. **EdX** Course: [Intro to TinyML](https://www.edx.org/professional-certificate/harvardx-tiny-machine-learning) Description: Learn about TinyML with this HarvardX course.
