bibliography:
- contents/core/introduction/introduction.bib
- contents/core/ai_for_good/ai_for_good.bib
- contents/core/benchmarking/benchmarking.bib
- contents/core/data_engineering/data_engineering.bib
- contents/core/dl_primer/dl_primer.bib
- contents/core/dnn_architectures/dnn_architectures.bib
- contents/core/efficient_ai/efficient_ai.bib
- contents/core/ml_systems/ml_systems.bib
- contents/core/frameworks/frameworks.bib
- contents/core/hw_acceleration/hw_acceleration.bib
- contents/core/ondevice_learning/ondevice_learning.bib
- contents/core/ops/ops.bib
- contents/core/optimizations/optimizations.bib
- contents/core/privacy_security/privacy_security.bib
- contents/core/responsible_ai/responsible_ai.bib
- contents/core/robust_ai/robust_ai.bib
- contents/core/sustainable_ai/sustainable_ai.bib
- contents/core/training/training.bib
- contents/core/workflow/workflow.bib
- contents/core/conclusion/conclusion.bib
crossref:
  appendix-delim: ':'
  appendix-title: Appendix
  custom:
  - key: vid
    kind: float
    latex-env: vid
    reference-prefix: Video
diagram:
  engine:
    asymptote: false
    dot: false
    mermaid: false
    tikz:
      execpath: lualatex
      header-includes:
      - \usepackage{tikz}
      - \usepackage{pgfplots}
      - \usepackage{pgf-pie}
      - \usepackage{amsmath}
      - \usepackage{amssymb}
      - \usepackage{xcolor}
      - \pgfplotsset{compat=1.9}
      - \usepgfplotslibrary{fillbetween}
      - \usetikzlibrary{angles}
      - \usetikzlibrary{arrows.meta}
      - \usetikzlibrary{arrows}
      - \usetikzlibrary{backgrounds}
      - \usetikzlibrary{bending}
      - \usetikzlibrary{calc}
      - \usetikzlibrary{fit}
      - \usetikzlibrary{intersections}
      - \usetikzlibrary{positioning}
      - \usetikzlibrary{shapes.geometric}
      - \usetikzlibrary{shapes}
      - \usetikzlibrary{quotes}
      - \usetikzlibrary{decorations.pathmorphing}
      - \usetikzlibrary{decorations.markings}
      - \usetikzlibrary{matrix}
      - \usepgfplotslibrary{dateplot}
      - \usepgfplotslibrary{polar}
      - \definecolor{Brown}{rgb}{0.65, 0.16, 0.16}
      - \definecolor{BrownL}{rgb}{0.6, 0.4, 0.2}
      - \definecolor{BrownLine}{rgb}{0.5, 0.3, 0.1}
      - \definecolor{BackColor}{RGB}{255,255,229}
      - \definecolor{BackLine}{RGB}{181,181,72}
      - \definecolor{BlueD}{RGB}{62,100,125}
      - \definecolor{BlueL}{RGB}{209,243,255}
      - \definecolor{BlueLine}{RGB}{34,148,189}
      - \definecolor{BrownL}{RGB}{233,222,220}
      - \definecolor{BrownLine}{RGB}{143,120,116}
      - \definecolor{Green}{rgb}{0.0, 0.5, 0.0}
      - \definecolor{GreenD}{RGB}{40,117,40}
      - \definecolor{GreenL}{RGB}{219,253,166}
      - \definecolor{GreenLine}{RGB}{73,89,56}
      - \definecolor{OliveL}{RGB}{230,227,191}
      - \definecolor{OliveLine}{RGB}{173,166,10}
      - \definecolor{OrangeL}{RGB}{250,212,175}
      - \definecolor{OrangeLine}{RGB}{255,127,76}
      - \definecolor{RedL}{RGB}{253,226,240}
      - \definecolor{RedLine}{RGB}{201,20,110}
      - \definecolor{Sepia}{rgb}{0.44, 0.26, 0.08}
      - \definecolor{TextColor}{RGB}{224,224,224}
      - \definecolor{VioletL}{RGB}{247,180,247}
      - \definecolor{VioletL2}{RGB}{243,243,255}
      - \definecolor{VioletLine}{RGB}{34,125,189}
      - \definecolor{VioletLine2}{RGB}{169,136,229}
      output-format: svg
editor:
  render-on-save: true
filter-metadata:
  cross-references:
    enabled: true
    file: data/cross_refs_final.json
  mlsysbook-ext/custom-numbered-blocks:
    icon-format: png
    icon-path: assets/images/icons/callouts
  part-summaries:
    enabled: true
    file: contents/parts/summaries.yml
  quiz-config:
    auto-discover-pdf: false
    file-pattern: '*_quizzes.json'
    scan-directory: contents/core
filters:
- filters/sidenote.lua
- filters/inject_parts.lua
- filters/inject_quizzes.lua
- pandoc-ext/diagram
- mlsysbook-ext/custom-numbered-blocks
- mlsysbook-ext/margin-video
- filters/margin-connections.lua
format:
  html:
    anchor-sections: true
    citation-location: margin
    citations-hover: false
    citeproc: true
    code-block-bg: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-height: 5
    fig-width: 7
    footnotes-hover: false
    highlight-style: assets/styles/custom-code.theme
    include-in-header:
      text: '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">


        <script async src="https://www.googletagmanager.com/gtag/js?id=G-M21L0CBCVN"></script>

        <script type="module"  src="/tools/scripts/ai_menu/dist/bundle.js" defer></script>

        <script type="module" src="/tools/scripts/ai_menu/dist/sqlite3-opfs-async-proxy-B_ImRJXp.js"></script>

        <script type="module" src="/tools/scripts/ai_menu/dist/sqlite3-worker1-bundler-friendly-CbDNa4by.js"></script>

        <script type="module" src="/tools/scripts/ai_menu/dist/worker-voUF5YDa.js"></script>

        <script src="/assets/scripts/sidebar-auto-collapse.js" defer></script>

        '
    language:
      title-block-author-single: Author, Editor & Curator
      title-block-published: Last Updated
    lightbox: true
    link-external-icon: false
    link-external-newwindow: true
    mermaid:
      theme: default
    number-depth: 3
    number-sections: false
    pagetitle: ML Systems Textbook
    reference-location: margin
    sidenote: true
    smooth-scroll: false
    theme:
    - default
    - assets/styles/style.scss
    title-prefix: ''
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-title: On this page
metadata-files:
- config/announcement.yml
mlsysbook-ext/custom-numbered-blocks:
  classes:
    callout-chapter-connection:
      group: chapter-connection
      label: Chapter connections
    callout-code:
      group: code-listing
      label: Code
    callout-definition:
      group: definition
      label: Definition
    callout-quiz-answer:
      group: quiz-answer
      label: 'Self-Check: Answer'
    callout-quiz-question:
      group: quiz-question
      label: 'Self-Check: Question'
    callout-resource-exercises:
      group: resource-exercises
      label: Exercises
    callout-resource-slides:
      group: resource-slides
      label: Listing
    callout-resource-videos:
      group: resource-videos
      label: Videos
  groups:
    chapter-connection:
      boxstyle: foldbox.simple
      collapse: true
      colors:
      - FDF2F7
      - A51C30
      numbered: false
    chapter-forward:
      boxstyle: foldbox.simple
      collapse: true
      colors:
      - FDF2F7
      - A51C30
      numbered: false
    chapter-recall:
      collapse: true
      colors:
      - FFF4E6
      - C06014
      numbered: false
    code-listing:
      collapse: false
      colors:
      - F2F4F8
      - D1D7E0
      numbered: false
    definition:
      collapse: false
      colors:
      - F0F8FF
      - 4682B4
      numbered: false
    quiz-answer:
      collapse: true
      colors:
      - E8F2EA
      - 4a7c59
    quiz-question:
      collapse: true
      colors:
      - F0F0F8
      - 5B4B8A
    resource-exercises:
      collapse: true
      colors:
      - E0F2F1
      - 20B2AA
      numbered: false
    resource-slides:
      collapse: true
      colors:
      - E0F2F1
      - 20B2AA
      numbered: false
    resource-videos:
      collapse: true
      colors:
      - E0F2F1
      - 20B2AA
      numbered: false
project:
  output-dir: _build/html
  post-render:
  - scripts/clean_svgs.py
  preview:
    browser: true
    navigate: true
  render:
  - index.qmd
  - contents/core/introduction/introduction.qmd
  type: website
website:
  back-to-top-navigation: true
  bread-crumbs: true
  comments:
    hypothesis:
      openSidebar: false
      theme: clean
  favicon: assets/images/icons/favicon.png
  google-analytics:
    anonymize-ip: true
    tracking-id: G-M21L0CBCVN
    version: 4
  navbar:
    background: light
    collapse: true
    collapse-below: md
    logo: assets/images/icons/favicon.png
    pinned: true
    right:
    - href: contents/labs/labs.qmd
      icon: code
      text: Labs
    - href: contents/labs/kits.qmd
      icon: box
      text: Kits
    - href: https://mlsysbook.ai/pdf
      icon: file-pdf
      target: _blank
      text: PDF
    - href: https://mlsysbook.ai/epub
      icon: book
      target: _blank
      text: EPUB
    - href: https://github.com/harvard-edge/cs249r_book
      icon: star
      target: _blank
      text: Star
    - href: https://opencollective.com/mlsysbook
      icon: heart
      target: _blank
      text: Support
    - icon: github
      menu:
      - href: https://github.com/harvard-edge/cs249r_book
        icon: pencil
        target: _blank
        text: Edit this page
      - href: https://github.com/harvard-edge/cs249r_book/issues/new
        icon: bug
        target: _blank
        text: Report an issue
      - href: https://github.com/harvard-edge/cs249r_book/discussions
        icon: chat
        target: _blank
        text: Discussions
      - href: https://github.com/harvard-edge/cs249r_book
        icon: code
        target: _blank
        text: View source
      text: GitHub
    search: true
    title: Machine Learning Systems
  page-footer:
    background: light
    border: true
    center: 'Written, edited and curated by Prof. Vijay Janapa Reddi (Harvard University)

      '
    left: '© 2024 Harvard University. Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC-BY-NC-SA
      4.0</a>

      '
    right:
    - aria-label: View source on GitHub
      href: https://github.com/harvard-edge/cs249r_book
      icon: github
    - aria-label: Star this repository
      href: https://github.com/harvard-edge/cs249r_book
      icon: star
  page-navigation: true
  reader-mode: false
  repo-url: https://github.com/harvard-edge/cs249r_book
  sidebar:
  - background: light
    collapse-level: 3
    contents:
    - href: index.qmd
      text: Homepage
    - href: contents/frontmatter/foreword.qmd
      text: Foreword
    - href: contents/frontmatter/about/about.qmd
    - href: contents/frontmatter/changelog/changelog.qmd
    - href: contents/frontmatter/acknowledgements/acknowledgements.qmd
    - href: contents/frontmatter/socratiq/socratiq.qmd
    - contents:
      - href: contents/core/introduction/introduction.qmd
      - href: contents/core/ml_systems/ml_systems.qmd
      - href: contents/core/dl_primer/dl_primer.qmd
      - href: contents/core/dnn_architectures/dnn_architectures.qmd
      id: foundations
      section: Systems Foundations
    - contents:
      - href: contents/core/workflow/workflow.qmd
      - href: contents/core/data_engineering/data_engineering.qmd
      - href: contents/core/frameworks/frameworks.qmd
      - href: contents/core/training/training.qmd
      id: design
      section: Design Principles
    - contents:
      - href: contents/core/efficient_ai/efficient_ai.qmd
      - href: contents/core/optimizations/optimizations.qmd
      - href: contents/core/hw_acceleration/hw_acceleration.qmd
      - href: contents/core/benchmarking/benchmarking.qmd
      id: performance
      section: Performance Engineering
    - contents:
      - href: contents/core/ops/ops.qmd
      - href: contents/core/ondevice_learning/ondevice_learning.qmd
      - href: contents/core/robust_ai/robust_ai.qmd
      - href: contents/core/privacy_security/privacy_security.qmd
      id: deployment
      section: Robust Deployment
    - contents:
      - href: contents/core/responsible_ai/responsible_ai.qmd
      - href: contents/core/sustainable_ai/sustainable_ai.qmd
      - href: contents/core/ai_for_good/ai_for_good.qmd
      id: trustworthy
      section: Trustworthy Systems
    - contents:
      - href: contents/core/conclusion/conclusion.qmd
      id: frontiers
      section: Frontiers of ML Systems
    - auto-collapse: true
      contents:
      - href: contents/labs/labs.qmd
      - href: contents/labs/kits.qmd
      - href: contents/labs/ide_setup.qmd
      id: labs-overview
      section: Hands-on Labs
    - auto-collapse: true
      contents:
      - href: contents/labs/arduino/nicla_vision/nicla_vision.qmd
      - href: contents/labs/arduino/nicla_vision/setup/setup.qmd
      - href: contents/labs/arduino/nicla_vision/image_classification/image_classification.qmd
      - href: contents/labs/arduino/nicla_vision/object_detection/object_detection.qmd
      - href: contents/labs/arduino/nicla_vision/kws/kws.qmd
      - href: contents/labs/arduino/nicla_vision/motion_classification/motion_classification.qmd
      id: arduino
      section: Arduino
    - auto-collapse: true
      contents:
      - href: contents/labs/seeed/xiao_esp32s3/xiao_esp32s3.qmd
      - href: contents/labs/seeed/xiao_esp32s3/setup/setup.qmd
      - href: contents/labs/seeed/xiao_esp32s3/image_classification/image_classification.qmd
      - href: contents/labs/seeed/xiao_esp32s3/object_detection/object_detection.qmd
      - href: contents/labs/seeed/xiao_esp32s3/kws/kws.qmd
      - href: contents/labs/seeed/xiao_esp32s3/motion_classification/motion_classification.qmd
      id: seeed-xiao
      section: Seeed XIAO ESP32S3
    - auto-collapse: true
      contents:
      - href: contents/labs/seeed/grove_vision_ai_v2/grove_vision_ai_v2.qmd
      - href: contents/labs/seeed/grove_vision_ai_v2/setup_and_no_code_apps/setup_and_no_code_apps.qmd
      - href: contents/labs/seeed/grove_vision_ai_v2/image_classification/image_classification.qmd
      - href: contents/labs/seeed/grove_vision_ai_v2/object_detection/object_detection.qmd
      id: grove-vision
      section: Grove Vision
    - auto-collapse: true
      contents:
      - href: contents/labs/raspi/raspi.qmd
      - href: contents/labs/raspi/setup/setup.qmd
      - href: contents/labs/raspi/image_classification/image_classification.qmd
      - href: contents/labs/raspi/object_detection/object_detection.qmd
      - href: contents/labs/raspi/llm/llm.qmd
      - href: contents/labs/raspi/vlm/vlm.qmd
      id: raspberry-pi
      section: Raspberry Pi
    - auto-collapse: true
      contents:
      - href: contents/labs/shared/shared.qmd
      - href: contents/labs/shared/kws_feature_eng/kws_feature_eng.qmd
      - href: contents/labs/shared/dsp_spectral_features_block/dsp_spectral_features_block.qmd
      id: shared-labs
      section: Shared
    - background: light
      collapse-level: 1
      contents: null
      id: resources
      style: floating
      title: Resources
    - text: '---'
    - auto-collapse: true
      contents:
      - href: contents/backmatter/resources/phd_survival_guide.qmd
        text: PhD Survival Guide
      id: resources
      section: Resources
    id: main-content
    style: floating
    title: Main Content
  title: ML Systems Textbook
