/**
 * Dynamic StaffML corpus statistics.
 *
 * Single source of truth for every user-visible "we have N questions across
 * M topics" number in the app. Derived at build time from
 * `src/data/vault-manifest.json`, which is regenerated by
 * `scripts/generate-manifest.py` whenever the corpus changes.
 *
 * If you find yourself typing a number like "8,053" or "79" into a component,
 * stop and import from here instead. The one and only reason copy like "4,800+
 * questions" ever appeared in the codebase was that the manifest lived in a
 * different file from the metadata that referenced it. This module closes that
 * gap permanently.
 */
import manifest from "@/data/vault-manifest.json";

// ─── Raw counts (numbers) ────────────────────────────────────
export const QUESTION_COUNT: number = manifest.questionCount;
export const TOPIC_COUNT: number = manifest.conceptCount;
export const AREA_COUNT: number = manifest.areaCount;

/**
 * Deployment tracks surfaced in the primary UI. The manifest's
 * trackDistribution also contains a "global" bucket for cross-track questions;
 * that is NOT a deployment track, so we exclude it from the public-facing
 * count. The four user-facing tracks are Cloud / Edge / Mobile / TinyML.
 */
const EXCLUDED_TRACK_KEYS = new Set(["global"]);
export const TRACK_COUNT: number = Object.keys(manifest.trackDistribution).filter(
  (k) => !EXCLUDED_TRACK_KEYS.has(k),
).length;

/** Bloom-aligned difficulty levels: L1, L2, L3, L4, L5, L6+ */
export const LEVEL_COUNT: number = Object.keys(manifest.levelDistribution).length;

// ─── Formatted strings (pre-formatted for copy) ──────────────
const intFormatter = new Intl.NumberFormat("en-US");

/** "8,053" — use this in all user-visible copy. */
export const QUESTION_COUNT_FORMATTED: string = intFormatter.format(QUESTION_COUNT);

/** "79" — for consistency with the formatter even though it fits in two digits. */
export const TOPIC_COUNT_FORMATTED: string = intFormatter.format(TOPIC_COUNT);

// ─── Release identity (strings) ──────────────────────────────
// vault-manifest.json is the single source of truth for "what release is
// this bundle?". It is emitted by vault-cli's emit_manifest() at build
// time from releases/<release_id>/release.json, so by construction the
// values here match the corpus the bundle ships with. Do NOT add
// fallbacks (?? "0.9.0", env-var defaults) — if the manifest is missing
// or malformed the build SHOULD fail, not silently mislabel the corpus.

/** Human-meaningful release tag, e.g. "0.1.0". Display this. */
export const RELEASE_ID: string = manifest.releaseId;

/** Full Merkle hash over the published YAML inputs (64 hex chars). */
export const RELEASE_HASH: string = manifest.releaseHash;

/** First 7 chars of RELEASE_HASH — display when room is tight. */
export const RELEASE_HASH_SHORT: string = manifest.releaseHash.slice(0, 7);

/** Schema spec version the YAML was validated against. Rarely changes. */
export const SCHEMA_VERSION: string = manifest.schemaVersion;

/** "What counts as published" policy version, bound into the release Merkle. */
export const POLICY_VERSION: string = manifest.policyVersion;

/** Build timestamp from vault-cli emit_manifest, ISO 8601. */
export const BUILD_DATE: string = manifest.buildDate;

// ─── Distributions (for charts and the radar widget) ─────────
export const TRACK_DISTRIBUTION = manifest.trackDistribution;
export const LEVEL_DISTRIBUTION = manifest.levelDistribution;

// ─── Canned copy fragments (the three strings that used to be hardcoded) ───
/**
 * Pre-assembled social/meta description line. This is what shows on Twitter,
 * LinkedIn, and SEO cards. Keep it short and accurate; it gets cached by
 * crawlers and takes a while to refresh once wrong.
 */
export const SOCIAL_DESCRIPTION = `Physics-grounded ML systems interview prep. ${QUESTION_COUNT_FORMATTED} questions across cloud, edge, mobile, and TinyML. Free, open source, runs entirely in your browser.`;

export const SOCIAL_DESCRIPTION_LONG = `${QUESTION_COUNT_FORMATTED} physics-grounded ML systems questions with napkin math verification. Free, open source, no accounts, runs entirely in your browser.`;

export const SOCIAL_IMAGE_ALT = `StaffML — ${QUESTION_COUNT_FORMATTED} ML systems interview questions`;
