from __future__ import annotations

import argparse
import shutil
from pathlib import Path
from typing import Any

import yaml

from mlperf.edu_cli import workload_run_selector
from mlperf.registry import Workload, load_registry


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Bootstrap or refresh the native suite/workload/variant layout from workloads.yaml."
    )
    parser.add_argument(
        "--source", default="workloads.yaml", help="Flat registry YAML to export."
    )
    parser.add_argument(
        "--output-dir", default="registry", help="Native registry output directory."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the native layout is current without writing files.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove the existing output suites directory before writing.",
    )
    args = parser.parse_args()

    workloads = load_registry(args.source)
    output_dir = Path(args.output_dir)
    expected = expected_files(workloads, output_dir)

    if args.check:
        return check_files(expected, output_dir)

    suites_dir = output_dir / "suites"
    if args.clean and suites_dir.exists():
        shutil.rmtree(suites_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"wrote {len(expected)} registry file(s) to {output_dir}")
    return 0


def expected_files(workloads: dict[str, Workload], output_dir: Path) -> dict[Path, str]:
    files: dict[Path, str] = {
        output_dir / "README.md": render_readme(workloads),
    }
    canonical_groups: dict[tuple[str, str], list[Workload]] = {}
    for workload in workloads.values():
        if workload.canonical_workload:
            canonical_groups.setdefault(
                (workload.suite, workload.canonical_workload), []
            ).append(workload)
            continue
        path = output_dir / "suites" / workload.suite / f"{workload.id}.yaml"
        files[path] = dump_yaml({"id": workload.id, **workload.raw})

    for (suite, canonical), variants in sorted(canonical_groups.items()):
        base_path = output_dir / "suites" / suite / canonical / "workload.yaml"
        files[base_path] = dump_yaml(
            {
                "id": canonical,
                "suite": suite,
                "variant_order": [str(workload.variant) for workload in variants],
            }
        )
        for workload in variants:
            raw = dict(workload.raw)
            raw.pop("canonical_workload", None)
            raw.pop("variant", None)
            variant_path = (
                output_dir
                / "suites"
                / suite
                / canonical
                / "variants"
                / f"{workload.variant}.yaml"
            )
            files[variant_path] = dump_yaml({"id": workload.id, **raw})
    return files


def render_readme(workloads: dict[str, Workload]) -> str:
    rows = [
        "| Suite | Workload | Internal ID | Public status |",
        "|---|---|---|---|",
    ]
    for workload in sorted(
        workloads.values(),
        key=lambda item: (item.suite, workload_run_selector(item), item.id),
    ):
        rows.append(
            f"| `{workload.suite}` | `{workload_run_selector(workload)}` | `{workload.id}` | `{workload.public_status}` |"
        )
    return "\n".join(
        [
            "# MLPerf EDU Native Registry",
            "",
            "This directory is the native suite/workload/variant registry layout.",
            "Edit these files first. `workloads.yaml` is a compatibility mirror generated by `tools/export_flat_registry.py`.",
            "`tools/export_registry_layout.py` is retained as a migration helper; normal edits should happen in this native layout and then refresh the generated flat mirror.",
            "Taxonomy claims fail closed. Keep an axis `unmeasured` unless its committed roofline sidecar and complete SHA-256 pass `tools/check_taxonomy.py`.",
            "",
            *rows,
            "",
        ]
    )


def check_files(expected: dict[Path, str], output_dir: Path) -> int:
    problems: list[str] = []
    for path, content in expected.items():
        if not path.exists():
            problems.append(f"missing {path}")
            continue
        if not same_file_content(path, content):
            problems.append(f"stale {path}")

    if output_dir.exists():
        expected_paths = set(expected)
        # Registry metadata that is authored, not derived from workload data:
        # suite-level titles/summaries consumed by tools/generate_docs.py.
        preserved = {output_dir / "suites.yaml"}
        expected_paths.update(preserved)
        extra = sorted(
            path for path in output_dir.rglob("*.yaml") if path not in expected_paths
        )
        extra.extend(
            path for path in output_dir.rglob("*.md") if path not in expected_paths
        )
        problems.extend(f"extra {path}" for path in extra)

    if problems:
        print("native registry layout is not current:")
        for problem in problems:
            print(f"- {problem}")
        print("run: python3 tools/export_registry_layout.py --clean")
        return 1

    print(f"native registry layout is current ({len(expected)} file(s))")
    return 0


def same_file_content(path: Path, expected: str) -> bool:
    actual = path.read_text(encoding="utf-8")
    if path.suffix in {".yaml", ".yml"}:
        return yaml.safe_load(actual) == yaml.safe_load(expected)
    return actual == expected


def dump_yaml(data: dict[str, Any]) -> str:
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True)


if __name__ == "__main__":
    raise SystemExit(main())
