# ╔═══════════════════════════════════════════════════════════════════════════════╗
# ║                        🚨 CRITICAL WARNING 🚨                                ║
# ║                     AUTOGENERATED! DO NOT EDIT!                              ║
# ║                                                                               ║
# ║  This file is AUTOMATICALLY GENERATED from source modules.                   ║
# ║  ANY CHANGES MADE HERE WILL BE LOST when modules are re-exported!            ║
# ║                                                                               ║
# ║  ✅ TO EDIT: src/XX_simd_ops/XX_simd_ops.py                         ║
# ║  ✅ TO EXPORT: Run 'tito module complete XX'                                 ║
# ║                                                                               ║
# ║  🛡️ STUDENT PROTECTION: This file contains optimized implementations.        ║
# ║     Editing it directly may break module functionality and training.         ║
# ║                                                                               ║
# ║  🎓 LEARNING TIP: Work in src/ (developers) or modules/ (learners)           ║
# ║     The tinytorch/ directory is generated code - edit source files instead!  ║
# ╚═══════════════════════════════════════════════════════════════════════════════╝
"""C++ SIMD Matrix Multiplication Bridge for TinyTorch.

Compiles the C++ kernels in cpp_simd_gemm.cpp on first use and calls them
through ctypes. This is an optional, hand-written extension: it is tracked in
git as-is and is not generated from src/.

The build is honest about what it produced. It tries OpenMP first, and if the
compiler has no OpenMP runtime (Apple clang without Homebrew's libomp, for
example) it builds the same kernel single-threaded. simd_build_info() says
which one you got.
"""

import ctypes
import os
import platform
import subprocess
import numpy as np

_DIR = os.path.dirname(__file__)
_LIB_PATH = os.path.join(_DIR, "libtinytorch_simd.so")
_CPP_SOURCE = os.path.join(_DIR, "cpp_simd_gemm.cpp")
_simd_lib = None
_build_info = {"built": False, "openmp": False, "command": None, "error": None}

_BASE_FLAGS = ["-O3", "-shared", "-fPIC", "-std=c++17"]


def _openmp_flags():
    """Compiler flags that enable OpenMP on this platform, or None."""
    if platform.system() == "Darwin":
        # Apple clang understands OpenMP pragmas but ships no runtime;
        # Homebrew's libomp (brew install libomp) provides one.
        for prefix in ("/opt/homebrew/opt/libomp", "/usr/local/opt/libomp"):
            if os.path.isdir(os.path.join(prefix, "lib")):
                return ["-Xpreprocessor", "-fopenmp", f"-I{prefix}/include",
                        f"-L{prefix}/lib", "-lomp", f"-Wl,-rpath,{prefix}/lib"]
        return None
    return ["-fopenmp"]


def _arch_flags():
    """Flags that let the compiler vectorize for the build machine."""
    flags = []
    if platform.machine() in ("x86_64", "AMD64"):
        flags += ["-mavx2", "-mfma"]  # arm64 needs nothing: NEON is always on
    if platform.system() == "Darwin":
        # A loop that calls std::tanh stays scalar unless the compiler has a
        # vector tanh to call; Accelerate provides one. Without this the fused
        # GELU runs about 7x slower (measured on an M5 Max, 2026-09-18).
        flags += ["-fveclib=Accelerate", "-framework", "Accelerate"]
    return flags


def _compile():
    """Build the shared library, with OpenMP if possible. Returns True on success."""
    tmp = _LIB_PATH + f".{os.getpid()}.tmp"
    attempts = []
    omp = _openmp_flags()
    if omp is not None:
        attempts.append((True, _BASE_FLAGS + _arch_flags() + omp))
    attempts.append((False, _BASE_FLAGS + _arch_flags()))

    for openmp, flags in attempts:
        cmd = ["c++"] + flags + [_CPP_SOURCE, "-o", tmp]
        try:
            res = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="replace")
        except OSError as e:  # no compiler on PATH
            _build_info["error"] = str(e)
            return False
        if res.returncode == 0:
            os.replace(tmp, _LIB_PATH)  # atomic, so a concurrent import never sees half a file
            _build_info.update(built=True, openmp=openmp, command=" ".join(cmd[:-2] + [_LIB_PATH]))
            return True
        _build_info["error"] = res.stderr.strip()
    return False


def compile_and_load_simd():
    """Compile the C++ kernels if needed and load them. Returns None if unavailable."""
    global _simd_lib
    if _simd_lib is not None:
        return _simd_lib

    stale = (not os.path.exists(_LIB_PATH)
             or os.path.getmtime(_LIB_PATH) < os.path.getmtime(_CPP_SOURCE))
    if stale and not _compile():
        return None

    try:
        lib = ctypes.CDLL(_LIB_PATH)
    except OSError as e:
        _build_info["error"] = str(e)
        return None

    f32p = ctypes.POINTER(ctypes.c_float)
    # void tinytorch_cpp_gemm(const float* A, const float* B, float* C, int M, int K, int N)
    lib.tinytorch_cpp_gemm.argtypes = [f32p, f32p, f32p, ctypes.c_int, ctypes.c_int, ctypes.c_int]
    lib.tinytorch_cpp_gemm.restype = None
    # void tinytorch_cpp_fused_bias_gelu(const float* X, const float* bias, float* Y, int total, int inner)
    lib.tinytorch_cpp_fused_bias_gelu.argtypes = [f32p, f32p, f32p, ctypes.c_int, ctypes.c_int]
    lib.tinytorch_cpp_fused_bias_gelu.restype = None
    # int tinytorch_cpp_num_threads(void)
    lib.tinytorch_cpp_num_threads.argtypes = []
    lib.tinytorch_cpp_num_threads.restype = ctypes.c_int

    if not _build_info["built"]:  # loaded a library built by an earlier process
        _build_info["built"] = True
    _build_info["threads"] = lib.tinytorch_cpp_num_threads()
    _build_info["openmp"] = _build_info["threads"] > 1 or _build_info["openmp"]
    _simd_lib = lib
    return _simd_lib


def has_simd_support() -> bool:
    """Returns True if the C++ library compiled and loaded."""
    return compile_and_load_simd() is not None


def simd_build_info() -> dict:
    """What the build produced: whether OpenMP is on, how many threads, and the
    compile command (None when an earlier process built the library)."""
    compile_and_load_simd()
    return dict(_build_info)


def _ptr(arr: np.ndarray):
    return arr.ctypes.data_as(ctypes.POINTER(ctypes.c_float))


def simd_matmul(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Cache-blocked, SIMD-vectorized matrix multiply (multi-threaded when built with OpenMP).

    Args:
        a: 2D array [M, K]; converted to contiguous float32
        b: 2D array [K, N]; converted to contiguous float32

    Returns:
        c: 2D float32 array [M, N]. Falls back to np.matmul if the library is unavailable.
    """
    a_c = np.ascontiguousarray(a, dtype=np.float32)
    b_c = np.ascontiguousarray(b, dtype=np.float32)
    M, K = a_c.shape
    K_b, N = b_c.shape
    if K != K_b:
        raise ValueError(f"Incompatible matrix dimensions: ({M}, {K}) x ({K_b}, {N})")

    lib = compile_and_load_simd()
    if lib is None:
        return np.matmul(a_c, b_c).astype(np.float32)

    c = np.empty((M, N), dtype=np.float32)
    lib.tinytorch_cpp_gemm(_ptr(a_c), _ptr(b_c), _ptr(c), M, K, N)
    return c


def simd_fused_bias_gelu(x: np.ndarray, bias: np.ndarray) -> np.ndarray:
    """y = GELU(x + bias) in one pass over memory (tanh approximation).

    Args:
        x: array [..., D]; converted to contiguous float32
        bias: array [D]

    Returns:
        float32 array with the shape of x.
    """
    x_c = np.ascontiguousarray(x, dtype=np.float32)
    b_c = np.ascontiguousarray(bias, dtype=np.float32)
    if b_c.shape != (x_c.shape[-1],):
        raise ValueError(f"bias must have shape ({x_c.shape[-1]},), got {b_c.shape}")
    lib = compile_and_load_simd()
    if lib is None:
        val = x_c + b_c
        return (0.5 * val * (1.0 + np.tanh(np.sqrt(2.0 / np.pi) * (val + 0.044715 * val ** 3)))).astype(np.float32)
    y = np.empty_like(x_c)
    lib.tinytorch_cpp_fused_bias_gelu(_ptr(x_c), _ptr(b_c), _ptr(y), x_c.size, x_c.shape[-1])
    return y
