#!/usr/bin/env python3
"""Build corpus_stats.json for paper figures from the **served-question** lineage.

**Preferred:** ``interviews/vault/vault.db`` — the same SQLite file that
``interviews/vault-cli/scripts/ship_d1.py`` serializes to Cloudflare D1 (``SELECT … FROM
questions`` / ``chains`` / ``chain_questions``). That is the data plane users hit.

**Fallback:** a generated monolithic ``corpus.json`` from ``vault build --local-json``
(see ``interviews/vault/ARCHITECTURE.md`` §11), plus ``chains.json`` for chain metadata
not embedded in the JSON in older shapes.

Input resolution:
  1. ``--db PATH`` or ``$PAPER_VAULT_DB`` or, if present, ``interviews/vault/vault.db``
  2. Else ``--json PATH``, else the first existing of
     ``interviews/staffml/src/data/corpus.json`` / ``interviews/vault/corpus.json``,
     with ``../vault/chains.json`` for chain registries (JSON path only).

  For a **tagged release** matching ``export-paper``, pass
  ``--db interviews/vault/releases/<v>/vault.db`` so figures match that DB exactly.

  ``make paper-full`` also runs ``vault export-paper`` for ``macros.tex``; use the
  same build so in-text and figure counts line up.

Run: python3 analyze_corpus.py  [--db PATH]  [--json PATH]
Writes: corpus_stats.json (``_meta`` includes ``source: vault_db`` or ``legacy_json``)
"""

import argparse
import hashlib
import json
import os
import sqlite3
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

import yaml

SCRIPTS_DIR = Path(__file__).parent
PAPER_DIR = SCRIPTS_DIR.parent
REPO_INTERVIEWS = PAPER_DIR.parent
VAULT_DIR = REPO_INTERVIEWS / "vault"
# Generated by `vault build --local-json` (not hand-edited; see vault/scripts/DEPRECATED.md)
STAFFML_CORPUS_JSON = REPO_INTERVIEWS / "staffml" / "src" / "data" / "corpus.json"
VAULT_CORPUS_JSON = VAULT_DIR / "corpus.json"
# Built by `vault build`; `ship_d1.py` re-serializes this file's `questions` rows to Cloudflare D1.
VAULT_DB = VAULT_DIR / "vault.db"
CHAINS_PATH = VAULT_DIR / "chains.json"
TAXONOMY_PATH = VAULT_DIR / "schema" / "taxonomy_data.yaml"
OUTPUT_PATH = PAPER_DIR / "corpus_stats.json"
ENV_VAULT_DB = "PAPER_VAULT_DB"

TRACKS = ["cloud", "edge", "mobile", "tinyml", "global"]
LEVELS = ["L1", "L2", "L3", "L4", "L5", "L6+"]
ZONES = [
    "recall", "analyze", "design", "implement",
    "diagnosis", "specification", "fluency",
    "evaluation", "realization", "optimization",
    "mastery",
]
BLOOM_LABELS = {
    "L1": "Remember", "L2": "Understand", "L3": "Apply",
    "L4": "Analyze", "L5": "Evaluate", "L6+": "Create",
}


def _input_fingerprint(p: Path) -> dict:
    b = p.read_bytes()
    return {
        "path": p.name,
        "bytes": len(b),
        "sha256_12": hashlib.sha256(b).hexdigest()[:12],
    }


def resolve_corpus_path() -> Path:
    """Prefer StaffML build output, then optional vault mirror (legacy path)."""
    if STAFFML_CORPUS_JSON.is_file():
        return STAFFML_CORPUS_JSON
    if VAULT_CORPUS_JSON.is_file():
        return VAULT_CORPUS_JSON
    raise SystemExit(
        "No generated corpus.json found. From the repo root run:\n"
        "  vault build --local-json\n"
        f"Then expect either:\n  {STAFFML_CORPUS_JSON}\n  {VAULT_CORPUS_JSON}"
    )


def build_meta(
    data_path: Path,
    source_kind: str,
    *,
    json_chains_path: Path | None = None,
) -> dict:
    """Provenance for corpus_stats.json — ignored by generate_figures data logic.

    `source_kind`: ``"vault_db"`` (D1/ship_p1 lineage) or ``"legacy_json"`` (monolithic export).
    """
    m: dict = {
        "generated_utc": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "pipeline": "analyze_corpus.py",
        "source": source_kind,
    }
    m["data"] = {
        **_input_fingerprint(data_path),
        "resolved_path": str(data_path.resolve()),
    }
    if source_kind == "legacy_json" and json_chains_path and json_chains_path.exists():
        m["chains_registry"] = _input_fingerprint(json_chains_path)
    if TAXONOMY_PATH.exists():
        m["taxonomy_data_yaml"] = _input_fingerprint(TAXONOMY_PATH)
    return m


def load_corpus_from_vault_db(db_path: Path) -> tuple[list[dict], list[dict]]:
    """Build corpus + chain structures from the same SQLite ``vault.db`` that ``ship_d1`` ships to D1.

    Rows in ``questions`` are already release-policy–filtered (see ``vault_cli.compiler``).
    Chains are read from ``chains`` + ``chain_questions`` in that database (not from ``chains.json``).
    """
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        rows = conn.execute(
            """
            SELECT id, title, topic, track, level, zone, competency_area, bloom_level, phase,
                   status, scenario, question, common_mistake, realistic_solution, napkin_math,
                   provenance, created_at, last_modified, file_path, content_hash, authors_json
            FROM questions
            """
        ).fetchall()
        corpus: list[dict] = []
        for r in rows:
            d = {k: r[k] for k in r.keys()}
            corpus.append(
                {
                    "id": d["id"],
                    "title": d.get("title") or "",
                    "topic": d.get("topic") or "",
                    "track": d.get("track") or "",
                    "level": d.get("level") or "",
                    "zone": d.get("zone") or "",
                    "competency_area": d.get("competency_area") or "",
                    "bloom_level": d.get("bloom_level") or "",
                    "phase": d.get("phase") or "",
                    "status": d.get("status") or "published",
                    "scenario": d.get("scenario") or "",
                    "question": d.get("question") or "",
                    "provenance": d.get("provenance") or "",
                    "details": {
                        "napkin_math": (d.get("napkin_math") or "") or "",
                        "common_mistake": (d.get("common_mistake") or "") or "",
                        "realistic_solution": (d.get("realistic_solution") or "") or "",
                    },
                }
            )
        chains: list[dict] = []
        cmeta = list(conn.execute("SELECT id, name, topic FROM chains").fetchall())
        for cid, cname, ctopic in cmeta:
            qrows = conn.execute(
                """
                SELECT cq.position, q.id, q.level, q.title, q.bloom_level, q.competency_area, q.scenario
                FROM chain_questions cq
                JOIN questions q ON q.id = cq.question_id
                WHERE cq.chain_id = ?
                ORDER BY cq.position
                """,
                (cid,),
            ).fetchall()
            member = []
            levels_list: list[str] = []
            for r in qrows:
                _pos, qid, lvl, title, bl, carea, _scen = r
                levels_list.append(lvl)
                member.append(
                    {
                        "id": qid,
                        "level": lvl,
                        "title": title or "",
                        "bloom": bl or "",
                        "bloom_level": bl or "",
                        "competency_area": carea or "",
                    }
                )
            first_area = (member[0].get("competency_area") or "") if member else ""
            chains.append(
                {
                    "id": cid,
                    "name": cname,
                    "topic": ctopic or "",
                    "questions": member,
                    "levels": levels_list,
                    "competency_area": first_area,
                }
            )
    finally:
        conn.close()
    return corpus, chains


def apply_export_paper_chain_metrics(db_path: Path, stats: dict) -> None:
    """Mutate ``stats`` so chain counts match ``vault export-paper`` / ``macros.tex``.

    The exporter (``release.export_paper_cmd``) defines:
    - ``chains_total`` = ``COUNT(DISTINCT chain_id)`` from ``chain_questions`` (chains
      with at least one link), not row count in ``chains``.
    - ``full`` / ``chains_full`` = number of chains whose membership count is >= 5
      (L1→L5 depth / ``numchainsFull`` in macros), *not* “all six Bloom ladder cells”.
    - ``by_length`` = histogram: how many chains have each exact link count.
    """
    total = stats["summary"]["total"]
    conn = sqlite3.connect(db_path)
    try:
        chains_total = int(
            conn.execute("SELECT COUNT(DISTINCT chain_id) AS n FROM chain_questions")
            .fetchone()[0]
        )
        questions_in_chains = int(
            conn.execute("SELECT COUNT(DISTINCT question_id) AS n FROM chain_questions")
            .fetchone()[0]
        )
        by_len_rows = conn.execute(
            "SELECT chain_id, COUNT(*) AS n FROM chain_questions GROUP BY chain_id"
        ).fetchall()
    finally:
        conn.close()
    length_hist: dict[int, int] = {}
    for _cid, n in by_len_rows:
        length_hist[n] = length_hist.get(n, 0) + 1
    chains_full = sum(1 for _cid, n in by_len_rows if n >= 5)
    by_length_str = {str(k): length_hist[k] for k in sorted(length_hist)}

    stats["summary"]["chains_total"] = chains_total
    stats["summary"]["chains_full"] = chains_full
    ch = stats["chains"]
    ch["total"] = chains_total
    ch["by_length"] = by_length_str
    ch["full_chains"] = chains_full
    ch["questions_in_chains"] = questions_in_chains
    ch["chain_coverage_pct"] = round(100.0 * questions_in_chains / total, 1) if total else 0.0


def classify_format(scenario: str) -> list[str]:
    s = scenario.lower()
    fmts = []
    if any(w in s for w in ["calculate", "compute", "estimate", "how many", "how much"]):
        fmts.append("calculation")
    if any(w in s for w in ["design", "architect", "propose", "how would you build"]):
        fmts.append("design")
    if any(w in s for w in ["explain", "what is", "define", "describe"]):
        fmts.append("conceptual")
    if any(w in s for w in ["optimize", "improve", "reduce", "speed up"]):
        fmts.append("optimization")
    if any(w in s for w in ["diagnose", "debug", "why is", "root cause", "fails"]):
        fmts.append("diagnosis")
    if any(w in s for w in ["compare", "trade-off", "tradeoff", "versus", " vs "]):
        fmts.append("tradeoff")
    return fmts if fmts else ["conceptual"]


def compute_all_stats(corpus: list, chains: list, taxonomy) -> dict:
    pub = [q for q in corpus if q.get("status", "published") == "published"]
    archived = [q for q in corpus if q.get("status") == "archived"]

    stats = {}

    # ── Summary ──────────────────────────────────────────────
    topic_set = set(q.get("topic", "") for q in pub if q.get("topic"))
    zone_set = set(q.get("zone", "") for q in pub if q.get("zone"))
    area_set = set(q.get("competency_area", "") for q in pub if q.get("competency_area"))

    full_chains = sum(
        1 for ch in chains
        if set(ch.get("levels", [])) >= {"L1", "L2", "L3", "L4", "L5", "L6+"}
    )

    stats["summary"] = {
        "total": len(pub),
        "published": len(pub),
        "archived": len(archived),
        "tracks": len(set(q.get("track") for q in pub)),
        "levels": len(LEVELS),
        "topics": len(topic_set),
        "zones": len(zone_set),
        "areas": len(area_set),
        "chains_total": len(chains),
        "chains_full": full_chains,
    }

    # ── Track × Level matrix ─────────────────────────────────
    matrix = defaultdict(lambda: defaultdict(int))
    for q in pub:
        matrix[q["track"]][q["level"]] += 1

    stats["track_level_matrix"] = {
        "tracks": TRACKS,
        "levels": LEVELS,
        "data": {t: {l: matrix[t][l] for l in LEVELS} for t in TRACKS},
        "track_totals": {t: sum(matrix[t][l] for l in LEVELS) for t in TRACKS},
    }

    # ── Competency areas ─────────────────────────────────────
    areas = Counter(q["competency_area"] for q in pub)
    stats["competency_areas"] = {a: c for a, c in areas.most_common()}

    # ── Zone distribution ────────────────────────────────────
    zone_counts = Counter(q.get("zone", "") for q in pub)
    stats["zone_distribution"] = {z: zone_counts.get(z, 0) for z in ZONES}

    # ── Zone × Level matrix ──────────────────────────────────
    zl_matrix = defaultdict(lambda: defaultdict(int))
    for q in pub:
        zl_matrix[q.get("zone", "")][q["level"]] += 1
    stats["zone_level_matrix"] = {
        z: {l: zl_matrix[z][l] for l in LEVELS} for z in ZONES
    }

    # ── Zone × Track matrix ──────────────────────────────────
    zt_matrix = defaultdict(lambda: defaultdict(int))
    for q in pub:
        zt_matrix[q.get("zone", "")][q["track"]] += 1
    stats["zone_track_matrix"] = {
        z: {t: zt_matrix[z][t] for t in TRACKS} for z in ZONES
    }

    # ── Topic distribution ───────────────────────────────────
    topic_counts = Counter(q.get("topic", "") for q in pub)
    stats["topic_distribution"] = {t: c for t, c in topic_counts.most_common()}

    # ── Bloom distribution ───────────────────────────────────
    bloom_counts = Counter(q.get("bloom_level", "") for q in pub)
    stats["bloom_distribution"] = dict(bloom_counts.most_common())

    # ── Field coverage ───────────────────────────────────────
    total = len(pub)
    stats["field_coverage"] = {
        "topic": sum(1 for q in pub if q.get("topic", "").strip()) / total,
        "zone": sum(1 for q in pub if q.get("zone", "").strip()) / total,
        "competency_area": sum(1 for q in pub if q.get("competency_area", "").strip()) / total,
        "napkin_math": sum(1 for q in pub if q.get("details", {}).get("napkin_math", "").strip()) / total,
        "common_mistake": sum(1 for q in pub if q.get("details", {}).get("common_mistake", "").strip()) / total,
        "realistic_solution": sum(1 for q in pub if q.get("details", {}).get("realistic_solution", "").strip()) / total,
        "bloom_level": sum(1 for q in pub if q.get("bloom_level", "").strip()) / total,
    }

    # ── Format distribution by level ─────────────────────────
    formats = ["calculation", "design", "conceptual", "optimization", "diagnosis", "tradeoff"]
    format_by_level = {}
    for level in LEVELS:
        lqs = [q for q in pub if q["level"] == level]
        fmt_counts = Counter()
        for q in lqs:
            for fmt in classify_format(q["scenario"]):
                fmt_counts[fmt] += 1
        fmt_total = sum(fmt_counts.values()) or 1
        format_by_level[level] = {
            "total_questions": len(lqs),
            "format_pct": {fmt: round(100 * fmt_counts.get(fmt, 0) / fmt_total, 1) for fmt in formats},
            "format_counts": {fmt: fmt_counts.get(fmt, 0) for fmt in formats},
        }
    stats["format_by_level"] = format_by_level

    # ── Coverage cube (track × level × area) ─────────────────
    cube = defaultdict(int)
    area_list = sorted(set(q["competency_area"] for q in pub if q["competency_area"]))
    for q in pub:
        if q.get("competency_area"):
            cube[(q["track"], q["level"], q["competency_area"])] += 1

    empty = sum(1 for t in TRACKS for l in LEVELS for a in area_list if cube.get((t, l, a), 0) == 0)
    underfilled = sum(1 for t in TRACKS for l in LEVELS for a in area_list if 0 < cube.get((t, l, a), 0) < 3)
    healthy = sum(1 for t in TRACKS for l in LEVELS for a in area_list if cube.get((t, l, a), 0) >= 3)

    stats["coverage_cube"] = {
        "empty_cells": empty,
        "underfilled_cells": underfilled,
        "healthy_cells": healthy,
        "total_cells": empty + underfilled + healthy,
    }

    # ── Level distribution percentages ───────────────────────
    level_dist = {}
    for t in TRACKS:
        t_total = sum(matrix[t][l] for l in LEVELS) or 1
        level_dist[t] = {l: round(100 * matrix[t][l] / t_total) for l in LEVELS}
    stats["level_distribution_pct"] = level_dist

    # ── Validation stats (computed from data, not hardcoded) ─
    validated_true = sum(1 for q in pub if q.get("validated") is True)
    validated_false = sum(1 for q in pub if q.get("validated") is False)
    has_issues = sum(1 for q in pub if q.get("validation_issues"))

    stats["validation"] = {
        "validated_true": validated_true,
        "validated_false": validated_false,
        "validated_null": total - validated_true - validated_false,
        "has_issues": has_issues,
        "validated_pct": round(100 * validated_true / total, 1),
    }

    # ── Chain stats ──────────────────────────────────────────
    chain_levels = Counter()
    for ch in chains:
        n = len(ch.get("questions", []))
        chain_levels[n] += 1

    chained_qids = set()
    for ch in chains:
        for entry in ch.get("questions", []):
            qid = entry["id"] if isinstance(entry, dict) else entry
            chained_qids.add(qid)

    stats["chains"] = {
        "total": len(chains),
        "by_length": {str(k): v for k, v in sorted(chain_levels.items())},
        "full_chains": full_chains,
        "questions_in_chains": len(chained_qids),
        "chain_coverage_pct": round(100 * len(chained_qids) / total, 1),
    }

    # ── Taxonomy graph stats ─────────────────────────────────
    if taxonomy:
        topics_data = taxonomy.get("topics", [])
        edge_types = Counter()
        for t in topics_data:
            for e in t.get("edges", []):
                edge_types[e["edge_type"]] += 1

        # Compute prerequisite depth
        prereq_adj = defaultdict(list)
        for t in topics_data:
            for e in t.get("edges", []):
                if e["edge_type"] == "prerequisite":
                    prereq_adj[t["id"]].append(e["target"])

        def depth(tid, visited=None):
            if visited is None:
                visited = set()
            if tid in visited:
                return 0
            visited.add(tid)
            children = prereq_adj.get(tid, [])
            if not children:
                return 0
            return 1 + max(depth(c, visited) for c in children)

        max_depth = max((depth(t["id"]) for t in topics_data), default=0)

        # Root topics (no prerequisites)
        has_prereqs = set()
        for t in topics_data:
            for e in t.get("edges", []):
                if e["edge_type"] == "prerequisite":
                    has_prereqs.add(t["id"])

        stats["taxonomy_graph"] = {
            "total_topics": len(topics_data),
            "total_edges": sum(edge_types.values()),
            "by_type": dict(edge_types),
            "max_prerequisite_depth": max_depth,
            "root_topics": len(topics_data) - len(has_prereqs),
            "topics_per_area": dict(Counter(t["area"] for t in topics_data).most_common()),
        }

    # ── Cross-track topic coverage ───────────────────────────
    topic_tracks = defaultdict(set)
    for q in pub:
        if q.get("topic"):
            topic_tracks[q["topic"]].add(q["track"])
    stats["cross_track_coverage"] = {
        t: sorted(tracks) for t, tracks in sorted(topic_tracks.items())
    }

    # ── Depth chain example (KV-cache) ───────────────────────
    kv_chain = next((ch for ch in chains if "kv-cache" in ch.get("topic", "")), None)
    if kv_chain:
        by_id = {q["id"]: q for q in corpus}
        stats["example_chain"] = {
            "topic": kv_chain["topic"],
            "competency_area": kv_chain.get("competency_area", "memory"),
            "questions": [
                {
                    "level": cq.get("level", by_id.get(cq.get("id", cq if isinstance(cq, str) else ""), {}).get("level", "?")),
                    "bloom": cq.get("bloom", ""),
                    "title": cq.get("title", by_id.get(cq.get("id", ""), {}).get("title", "?")),
                    "scenario_preview": by_id.get(
                        cq["id"] if isinstance(cq, dict) else cq, {}
                    ).get("scenario", "")[:100],
                }
                for cq in kv_chain["questions"]
            ],
        }

    return stats


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Build corpus_stats.json for paper figures. Prefer vault.db (D1 lineage) when present.",
    )
    ap.add_argument(
        "--db",
        type=Path,
        default=None,
        help="Path to vault.db (same SQLite that ship_d1.py loads for D1).",
    )
    ap.add_argument(
        "--json",
        type=Path,
        default=None,
        help="Path to a generated corpus.json; if set, skips default vault.db auto-detection.",
    )
    args = ap.parse_args()

    taxonomy = None
    if TAXONOMY_PATH.exists():
        taxonomy = yaml.safe_load(TAXONOMY_PATH.read_text())

    db_path: Path | None = None
    if args.db is not None:
        db_path = args.db
        if not db_path.is_file():
            raise SystemExit(f"not found: {db_path}")
    elif args.json is None and os.environ.get(ENV_VAULT_DB):
        p = Path(os.environ[ENV_VAULT_DB]).expanduser()
        if p.is_file():
            db_path = p
    elif args.json is None and VAULT_DB.is_file():
        db_path = VAULT_DB

    if db_path is not None:
        corpus, chains = load_corpus_from_vault_db(db_path)
        data_path = db_path
        source_kind = "vault_db"
        print(f"Using vault.db (D1 data plane lineage): {data_path.resolve()}", flush=True)
    else:
        corpus_path = args.json if args.json is not None else resolve_corpus_path()
        if not corpus_path.is_file():
            raise SystemExit(f"not found: {corpus_path}")
        corpus = json.loads(corpus_path.read_text())
        chains = json.loads(CHAINS_PATH.read_text()) if CHAINS_PATH.exists() else []
        data_path = corpus_path
        source_kind = "legacy_json"
        print(f"Using generated corpus.json: {data_path.resolve()}", flush=True)

    stats = compute_all_stats(corpus, chains, taxonomy)
    if db_path is not None:
        apply_export_paper_chain_metrics(db_path, stats)
    stats["_meta"] = build_meta(
        data_path,
        source_kind,
        json_chains_path=CHAINS_PATH if source_kind == "legacy_json" else None,
    )
    OUTPUT_PATH.write_text(json.dumps(stats, indent=2))
    s = stats["summary"]
    print(f"Wrote {OUTPUT_PATH} ({len(stats)} sections)")
    print(f"  Questions: {s['total']}")
    print(f"  Topics: {s['topics']}, Zones: {s['zones']}, Areas: {s['areas']}")
    print(
        f"  Chains: {s['chains_total']} distinct in chain_questions, "
        f"{s['chains_full']} with length >= 5 (export-paper / macros def)"
    )
    print(f"  Validated: {stats['validation']['validated_pct']}%")
    cc = stats["coverage_cube"]
    print(
        f"  Coverage: {cc['healthy_cells']} healthy, "
        f"{cc['underfilled_cells']} underfilled, {cc['empty_cells']} empty"
    )


if __name__ == "__main__":
    main()
