"use client";

import { ChainInfo } from "@/lib/corpus";
import { getLevelDef } from "@/lib/levels";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import clsx from "clsx";

export default function ChainStrip({ chain, onNavigate }: {
  chain: ChainInfo;
  onNavigate: (questionId: string) => void;
}) {
  const isFirst = chain.position <= 0;
  const isLast = chain.position >= chain.total - 1;
  const prevQ = !isFirst ? chain.questions[chain.position - 1] : null;
  const nextQ = !isLast ? chain.questions[chain.position + 1] : null;
  const prevDef = prevQ ? getLevelDef(prevQ.level) : null;
  const nextDef = nextQ ? getLevelDef(nextQ.level) : null;

  return (
    <div className="border-t border-border pt-4 mt-1">
      {/* Progress dots */}
      <div className="flex items-center gap-2 mb-3">
        <span className="text-[10px] font-mono text-textTertiary uppercase tracking-wide">
          Part {chain.position + 1} of {chain.total}
        </span>
        {chain.tier === "secondary" && (
          <span
            className="text-[9px] font-mono text-textTertiary uppercase tracking-wide px-1.5 py-0.5 rounded border border-borderSubtle"
            title="Alternative path — generated by the second-pass coverage build."
          >
            alt path
          </span>
        )}
        <div className="flex items-center gap-1">
          {chain.questions.map((q, i) => {
            const def = getLevelDef(q.level);
            return (
              <button
                key={q.id}
                onClick={() => onNavigate(q.id)}
                title={`${q.level} ${def.name}: ${q.title}`}
                className="group"
              >
                <div
                  className={clsx(
                    "w-3 h-3 rounded-full border-2 transition-all",
                    i === chain.position
                      ? "scale-125"
                      : i < chain.position
                      ? "opacity-60"
                      : "opacity-30"
                  )}
                  style={{
                    borderColor: def.color,
                    backgroundColor: i <= chain.position ? def.color : "transparent",
                  }}
                />
              </button>
            );
          })}
        </div>
      </div>

      {/* Previous/next question previews. Showing both directions makes the
          chain feel like a navigable path rather than a one-way suggestion. */}
      <div className="grid gap-2 sm:grid-cols-2">
        {prevQ && prevDef ? (
          <ChainNavCard
            label="Previous part"
            question={prevQ}
            color={prevDef.color}
            direction="prev"
            onClick={() => onNavigate(prevQ.id)}
          />
        ) : (
          <div className="hidden sm:flex items-center gap-2 px-3 py-2.5 rounded-lg bg-surface/40 border border-borderSubtle text-[12px] text-textTertiary">
            Start of chain
          </div>
        )}

        {nextQ && nextDef ? (
          <ChainNavCard
            label="Next part"
            question={nextQ}
            color={nextDef.color}
            direction="next"
            onClick={() => onNavigate(nextQ.id)}
          />
        ) : (
          <div className="flex items-center gap-2 px-3 py-2.5 rounded-lg bg-accentGreen/5 border border-accentGreen/20">
            <CheckCircle2 className="w-4 h-4 text-accentGreen shrink-0" />
            <span className="text-[13px] text-accentGreen font-medium">Chain complete</span>
          </div>
        )}
      </div>
    </div>
  );
}

function ChainNavCard({
  label,
  question,
  color,
  direction,
  onClick,
}: {
  label: string;
  question: ChainInfo["questions"][number];
  color: string;
  direction: "prev" | "next";
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg bg-surface border border-borderSubtle hover:border-borderHighlight hover:bg-surfaceHover transition-all text-left group"
    >
      {direction === "prev" && (
        <ArrowLeft className="w-4 h-4 text-textMuted group-hover:text-textPrimary shrink-0 transition-colors" />
      )}
      <div
        className="w-6 h-6 rounded-md flex items-center justify-center shrink-0"
        style={{ backgroundColor: `${color}20`, border: `1px solid ${color}40` }}
      >
        <span className="text-[9px] font-bold font-mono" style={{ color }}>
          {question.level}
        </span>
      </div>
      <div className="flex-1 min-w-0">
        <span className="text-[12px] text-textTertiary block">{label}</span>
        <span className="text-[13px] text-textPrimary font-medium truncate block">{question.title}</span>
      </div>
      {direction === "next" && (
        <ArrowRight className="w-4 h-4 text-textMuted group-hover:text-textPrimary shrink-0 transition-colors" />
      )}
    </button>
  );
}
