name: Build Linux Container Simple

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: harvard-edge/cs249r_book/quarto-linux
  CONTAINER_TAG: latest
  DOCKERFILE_PATH: ./docker/build-quarto-linux/Dockerfile
  CONTEXT_PATH: .

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Linux container
        run: |
          echo "Building Linux container..."
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_TAG }} -f ${{ env.DOCKERFILE_PATH }} ${{ env.CONTEXT_PATH }}

      - name: Push Linux container
        run: |
          echo "Pushing container to registry..."
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_TAG }}

      - name: Build Complete
        run: |
          echo "Linux container build completed successfully!"
          echo "Container pushed to: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.CONTAINER_TAG }}"
