name: 'Build Quarto'
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Render HTML
        continue-on-error: true
        id: html_build
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Check HTML Build Status
        if: always()
        run: |
          if [ "${{ steps.html_build.outcome }}" == "success" ]; then
            echo "✅ HTML build successful"
          else
            echo "⚠️ HTML build failed"
            exit 1
          fi

      - name: Render PDF
        continue-on-error: true
        id: pdf_build
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: titlepage-pdf

      - name: Check PDF Build Status
        if: always()
        run: |
          if [ "${{ steps.pdf_build.outcome }}" == "success" ]; then
            echo "✅ PDF build successful"
          else
            echo "⚠️ PDF build failed but workflow continuing"
          fi

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: _book-${{ inputs.os }}
          path: |
            _book
            *.pdf
          retention-days: 7