name: Check for build (Ubuntu)

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install TinyTeX
        run: quarto install tinytex
      - name: Build on Ubuntu
        run: quarto render
      - name: Upload artifact from Ubuntu
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: _book-ubuntu
          path: _book

