name: Check for build (Ubuntu)

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.13"

      - name: Install TinyTeX
        run: |
          quarto install tinytex
          echo "$HOME/.TinyTeX/bin/x86_64-linux" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpangoft2-1.0-0 \
            fonts-dejavu \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libcogl-pango-dev \
            pango1.0-tools \
            libcairo2 \

      - name: Install Inkscape
        run: |
          sudo add-apt-repository ppa:inkscape.dev/stable -y
          sudo apt-get update
          sudo apt-get install inkscape -y

      - name: Debug Inkscape
        run: inkscape --version  # Check Inkscape installation

      - name: Build on Ubuntu
        run: |
          quarto render  

      - name: Upload artifact from Ubuntu
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: _book-ubuntu
          path: _book

