name: 'Deploy to GitHub Pages'
on:
  workflow_call:
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Double-check we're on main
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.13"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any requirements for gs_compress_pdf.py here

      - name: Render Book
        run: |
          quarto render
          if [ $? -ne 0 ]; then
            echo "❌ Quarto render failed!"
            exit 1
          fi
          echo "✅ Quarto render completed successfully."

      - name: Compress PDF
        run: |
          python3 ./scripts/quarto_publish/gs_compress_pdf.py \
            -i ./_book/Machine-Learning-Systems.pdf \
            -o ./_book/ebook.pdf \
            -s "/ebook"
          if [ $? -ne 0 ]; then
            echo "❌ PDF compression failed!"
            exit 1
          fi
          echo "✅ PDF compression completed successfully."

      - name: Replace Original PDF
        run: |
          mv ./_book/ebook.pdf ./_book/Machine-Learning-Systems.pdf
          if [ $? -ne 0 ]; then
            echo "❌ Failed to replace original PDF!"
            exit 1
          fi
          echo "✅ PDF replaced successfully."

      - name: Publish to GitHub Pages
        run: |
          quarto publish --no-render gh-pages
          if [ $? -ne 0 ]; then
            echo "❌ Publishing to gh-pages failed!"
            exit 1
          fi
          echo "✅ Published to gh-pages successfully."