name: 'Dev Branch Build'

on:
  workflow_dispatch:  # Enables manual triggering
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: 'development'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/setup-quarto.yml
        with:
          os: ubuntu-latest
          
      - name: Build
        uses: ./.github/workflows/build-quarto.yml
        with:
          os: ubuntu-latest

      - name: Deploy to Dev Site
        if: inputs.environment == 'development'
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '_book'
          destination-github-username: 'harvard-edge'
          destination-repository-name: 'cs249r_book_dev'
          user-email: khoshnevis.naeem@gmail.com
          target-branch: 'main'
          target-directory: 'docs'