name: Test Inkscape SVG Conversion

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-inkscape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Install Inkscape
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape
          inkscape --version
      
      - name: Install font dependencies
        run: |
          sudo apt-get install -y \
            fonts-freefont-ttf \
            fonts-liberation \
            fontconfig
          sudo fc-cache -f -v
      
      - name: Create test SVG
        run: |
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><circle cx="50" cy="50" r="40" fill="red"/></svg>' > test.svg
          cat test.svg
      
      - name: Test SVG to PNG conversion
        run: |
          inkscape test.svg --export-type=png --export-filename=test.png
          ls -la test.png
          file test.png
      
      - name: Test SVG to PDF conversion
        continue-on-error: true
        run: |
          echo "Attempting SVG to PDF conversion..."
          inkscape test.svg --export-type=pdf --export-filename=test.pdf
          if [ -f test.pdf ]; then
            echo "✅ SVG to PDF conversion succeeded"
            ls -la test.pdf
            file test.pdf
          else
            echo "❌ SVG to PDF conversion failed"
          fi
      
      - name: Test rsvg-convert as alternative
        run: |
          echo "Installing rsvg-convert..."
          sudo apt-get install -y librsvg2-bin
          
          echo "Converting SVG to PDF with rsvg-convert..."
          rsvg-convert -f pdf -o rsvg-test.pdf test.svg
          
          if [ -f rsvg-test.pdf ]; then
            echo "✅ rsvg-convert SVG to PDF conversion succeeded"
            ls -la rsvg-test.pdf
            file rsvg-test.pdf
          else
            echo "❌ rsvg-convert SVG to PDF conversion failed"
          fi
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: svg-conversion-results
          path: |
            *.svg
            *.png
            *.pdf
          retention-days: 1