name: 'Link Check'
on:
  workflow_dispatch:  # Enables manual triggering
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  check-links:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Check Links
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: --verbose --no-progress './**/*.qmd' './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}