name: 'Link Check'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Links
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          args: --verbose --no-progress './**/*.qmd' './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}