# .github/workflows/lint-markdown.yml
name: 'Lint Markdown'

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm init -y
          npm install markdownlint-cli

      - name: Run Markdown Linting
        id: lint
        run: |
          output=$(npx markdownlint --config .github/workflows/markdown_linter/.mdlintconfig.yml \
                              --ignore-path .github/workflows/markdown_linter/.mdlintignore \
                              "**/*.qmd" 2>&1) || {
            echo "::error::Markdown linting failed"
            echo "$output"
            exit 1
          }
          
          if [ -z "$output" ]; then
            echo "✅ Markdown linting passed successfully"
          fi
