name: 'Lint Markdown'

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli
        run: |
          npm install -g markdownlint-cli

      - name: Run Markdown Linting
        id: lint
        run: |
          output=$(markdownlint --config .markdownlint.json \
                                --ignore-path .markdownlintignore \
                                "**/*.qmd" 2>&1) || {
            echo "::error::Markdown linting failed"
            echo "$output"
            exit 1
          }
          
          if [ -z "$output" ]; then
            echo "✅ Markdown linting passed successfully"
          fi
