name: 'Production Build'

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: 'production'

jobs:
  verify-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: true  # For production, we want to fail fast
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/setup-quarto.yml
        with:
          os: ${{ matrix.os }}
          
      - name: Build
        uses: ./.github/workflows/build-quarto.yml
        with:
          os: ${{ matrix.os }}

  deploy-production:
    needs: verify-build
    runs-on: ubuntu-latest
    environment: production
    if: inputs.environment == 'production'
    
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/setup-quarto.yml
        with:
          os: ubuntu-latest
          
      - name: Build and Deploy
        uses: ./.github/workflows/build-quarto.yml
        with:
          os: ubuntu-latest