name: Linting Quarto Markdown files
on:
    push:
    pull_request:

jobs:
    lint-qmd-files:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Installing GitHub CLI
              run: |
                  sudo apt -y update && sudo apt -y upgrade
                  sudo apt -y install software-properties-common
                  sudo apt install -y gh jq nodejs npm

            - name: Installing Markdown Linter
              run: |
                  sudo npm install -g markdownlint-cli

            - name: Markdown linting job has been triggered
              run: |
                  echo "The job was automatically triggered by a ${{ github.event_name }} event."

            - name: Running markdown linter
              run: |
                  markdownlint --config .github/workflows/markdown_linter/.mdlintconfig.yml --ignore-path .github/workflows/markdown_linter/.mdlintignore ./
                  ret=$?
                  if [ $ret -eq 1 ]; then
                    echo "Linting failed. Please correct any errors and run the job again."
                    exit 1
                  fi
