name: 'PR Validation'

on:
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  lint:
    needs: checkout
    uses: ./.github/workflows/lint-markdown.yml

  validate:
    needs: [checkout, lint]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/setup-quarto.yml
        with:
          os: ${{ matrix.os }}
          
      - name: Build
        uses: ./.github/workflows/build-quarto.yml
        with:
          os: ${{ matrix.os }}