name: 'Quarto Check'
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  check-quarto:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Check Quarto syntax
        run: |
          quarto check