name: 'Setup Quarto Environment'
on:
  workflow_call:
    inputs:
      quarto-version:
        required: false
        type: string
        default: '1.7.13'
      r-version:
        required: false
        type: string
        default: '4.2'
      os:
        required: true
        type: string

jobs:
  setup:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: ${{ inputs.quarto-version }}

      - name: Install TinyTeX
        shell: bash
        run: |
          quarto install tinytex
          if [ "${{ inputs.os }}" = "windows-latest" ]; then
            echo "$HOME/.TinyTeX/bin/windows" >> $GITHUB_PATH
          else
            echo "$HOME/.TinyTeX/bin/x86_64-linux" >> $GITHUB_PATH
          fi

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ inputs.r-version }}

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/R/library
          key: ${{ runner.os }}-r-${{ hashFiles('**/install_packages.R') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R Packages
        run: Rscript install_packages.R

      - name: Install Linux Dependencies
        if: inputs.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpangoft2-1.0-0 \
            fonts-dejavu \
            fonts-freefont-ttf \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libcogl-pango-dev \
            pango1.0-tools \
            libcairo2 \
            gdk-pixbuf2.0-bin \
            libgdk-pixbuf2.0-dev \
            librsvg2-bin

      - name: Install Inkscape (Linux)
        if: inputs.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository ppa:inkscape.dev/stable -y
          sudo apt-get update
          sudo apt-get install inkscape -y

      - name: Install Inkscape (Windows)
        if: inputs.os == 'windows-latest'
        run: choco install inkscape -y