name: 'Structure Check'

# Set retention period to 7 days
env:
  GITHUB_ACTIONS_RETENTION_DAYS: 7

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check Required Files
        run: |
          if [ ! -f "quarto/_quarto.yml" ]; then
            echo "❌ Missing quarto/_quarto.yml"
            exit 1
          fi
          if [ ! -f "quarto/index.qmd" ]; then
            echo "❌ Missing quarto/index.qmd"
            exit 1
          fi
          echo "✅ Structure check passed"