name: 'Structure Check'
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  check-structure:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Check Required Files
        run: |
          if [ ! -f "_quarto.yml" ]; then
            echo "Missing _quarto.yml"
            exit 1
          fi
          if [ ! -f "index.qmd" ]; then
            echo "Missing index.qmd"
            exit 1
          fi