# Foreword {.unnumbered}

<style>
.italic-section {
  font-style: italic;
}
</style>

<div class="italic-section">

AI is set to dramatically transform the world, much like computers and the Internet revolutionized every aspect of society in the 20th century. From AI systems capable of generating creative content to those accelerating scientific breakthroughs in drug discovery, AI is ushering in a new era—one that may prove even more profound in scope and impact.

With such transformative power comes an equally great responsibility. Just as we expect large-scale, big-tech AI R&D organizations to wield their influence ethically, those of us in academia bear a parallel responsibility: to share our knowledge openly, ensuring it benefits everyone, not just a select few. This conviction led to the creation of this book---an open-source resource aimed at making AI education, particularly in AI engineering and systems, inclusive and accessible to everyone.

My passion for creating, curating, and editing this content has been inspired by great textbooks that have influenced my personal and academic journey. Whether I studied them cover to cover or drew insights from key passages, these resources shaped the way I think. I think back to the books that shaped my journey: works by Turing Award winners like David Patterson and John Hennessy, pioneers in computer system design, and the foundational papers from luminaries like Yann LeCun, Geoffrey Hinton, and Yoshua Bengio. My hope is that this book inspires students to chart their unique paths.

As I reflect on the possibilities of harnessing this powerful technology, I am optimistic about what lies ahead for AI and its engineering discipline. AI can democratize access to knowledge, solve global challenges, and inspire creativity in ways we've yet to imagine. To achieve that, however, we must train the next generation of AI engineers and practitioners in ML systems---put simply, astronauts inspire us to reach for the stars, but rocket scientists are the ones that make the journey possible---similarly, skilled AI systems engineers lay the foundation for realizing even the boldest AI visions.

As I navigated through the process of creating this work, I found opportunities to reflect on the challenges and complexities inherent in the field. I am a student of my own writing, and every chapter of this book has taught me something new. For educators, I hope it serves as a valuable resource, addressing gaps in teaching materials within the AI systems domain. For practitioners, my hope is to provide you an enduring guide that bridges principles and practices and stands the test of time.

I am committed to keeping this book updated. Knowing that even one learner benefits from its content motivates me to continually refine and expand it. To that end, if there's one thing I ask of readers, it's this: show your support by starring this book's GitHub repository. You can do it [here](https://github.com/harvard-edge/cs249r_book). Each star ⭐ signals that this mission matters, whether you're a student just beginning your journey or an educator sharing these resources. Together, we can grow this community of learners, educators and practitioners to create a positive impact and ensure that AI benefits everyone. This small act is more than symbolic—it helps demonstrate the importance of making AI systems knowledge globally accessible. 

This book is dedicated to the loving memory of my late father. His passion for education, endless curiosity, generosity in sharing knowledge, and unwavering commitment to excellence inspire me daily to strive for the very best in all I do. It is also dedicated to teachers and mentors everywhere, whose tireless efforts and guidance transform lives every day. Your selfless contributions inspire me.

— Prof. Vijay Janapa Reddi

</div>